/* ═══════════════════════════════════════════════
   FAQ 頁多語擴充字典 — 合併進 i18n.js 的 DICT
   階段：框架(4語) + 英文問答(完整)
   日/韓/簡問答後續補上（缺漏會自動回退中文）
════════════════════════════════════════════════ */
(function () {
  if (typeof DICT === 'undefined') return;

  const FAQ = {
    /* ───── 框架 chrome（4 語）───── */
    en: {
      'faq.heroTitle':'Penghu Travel FAQ — 100 Questions',
      'faq.heroDesc':'First time in Penghu? How to get there, when to go, what to do, eat and budget? Our local agency answers the 100 most-asked questions in one place.',
      'faq.tocTraffic':'🚢 Getting There','faq.tocSeason':'☀️ Season & Weather','faq.tocStay':'🏨 Stay','faq.tocSpot':'📸 Attractions','faq.tocIsland':'🏝️ Island Hopping','faq.tocWater':'🤿 Water Activities','faq.tocFood':'🍤 Food','faq.tocFamily':'👨‍👩‍👧 Family','faq.tocPlan':'💰 Budget & Planning','faq.tocInfo':'🎵 Festival & Tips',
      'faq.catTraffic':'Transport & Arrival','faq.catSeason':'Best Season & Weather','faq.catStay':'Accommodation','faq.catSpot':'Attractions','faq.catIsland':'Island Hopping','faq.catWater':'Water Activities','faq.catFood':'Food','faq.catFamily':'Family & Kids','faq.catPlan':'Budget & Planning','faq.catInfo':'Festival & Practical Info',
      'faq.ctaTitle':'Still have questions?','faq.ctaDesc':'Whether it’s itinerary planning, budget or custom requests, our local Penghu team is happy to help.','faq.ctaConsult':'Online Enquiry','faq.ctaLine':'LINE Chat','faq.ctaTours':'View Tours',
      /* ── 問答 ── */
      'faq.q1':'How do I get to Penghu?','faq.a1':'Penghu is an offshore island, reached mainly by plane or ferry. The fastest way is a domestic flight to Magong Airport (about 40–50 min); to save money, take a ferry from Chiayi Budai Port or Kaohsiung. We can help plan the smoothest route from your departure city.',
      'faq.q2':'Which airports in Taiwan have flights to Penghu?','faq.a2':'Flights to Penghu (Magong Airport) mainly depart from Taipei Songshan, Taichung, Chiayi, Tainan and Kaohsiung, operated by Mandarin and UNI Air. Frequency varies by season; book early in peak season.',
      'faq.q3':'How long is the flight to Penghu?','faq.a3':'Flights from western Taiwan to Magong take about 35–50 minutes — the fastest and most comfortable option, with little risk of motion sickness, ideal for elderly travelers and children.',
      'faq.q4':'Is there a ferry to Penghu? Where does it depart?','faq.a4':'Yes. The most common route is from Chiayi Budai Port to Magong, with services also from Kaohsiung. The Budai crossing takes about 1.5–2 hours; schedules and fares vary by season and operator.',
      'faq.q5':'Will I get seasick on the ferry?','faq.a5':'Modern ferries are large and stable, smooth in calm seas, but can rock when waves are higher. If you’re prone to seasickness, take medication in advance, choose a mid-rear seat, or simply fly for peace of mind.',
      'faq.q6':'Is it better value to fly or take the ferry?','faq.a6':'Flying is fast and comfortable but pricier (especially in summer); ferries are cheaper with sea views but slower and more weather-dependent. We’ll compare flight and ferry packages to suit your budget and group size.',
      'faq.q7':'How far is Magong Airport from the city?','faq.a7':'Magong Airport is about 7 km / a 15-minute drive from the city. You can take a taxi, rent a car, or arrange a private transfer with us so someone meets you on arrival.',
      'faq.q8':'Is Penghu good for self-driving? Do I need to rent a vehicle?','faq.a8':'Penghu’s attractions are spread out, so self-driving or renting a scooter is the mainstream way to get around. If you’d rather not drive, our tours include a private vehicle and local guide for relaxed point-to-point transfers.',
      'faq.q9':'What should I know about renting a scooter in Penghu?','faq.a9':'You’ll need a valid license; inspect and photograph the scooter before renting. Penghu is windy and some roads are gravelly, so wear a helmet, slow down, and take extra care in the rain.',
      'faq.q10':'Does Penghu have buses or public transport?','faq.a10':'There are buses, but they’re infrequent with limited routes, so relying on them alone is restrictive. Most travelers rent a vehicle, charter a car, or join a tour with transfers for far more flexibility.',
      'faq.q11':'Are taxis convenient in Penghu?','faq.a11':'Taxis are easy to find in the city and at the airport, but harder to flag at remote attractions, so book ahead. For multiple stops or island hopping, a charter or tour is usually more cost-effective and time-saving.',
      'faq.q12':'How early should I book flights and ferries for a summer trip?','faq.a12':'July–August and long weekends are super peak — flights, ferries and accommodation sell out fast, so book 1–2 months ahead; the earlier the better for choice and price. Let us handle your flight-and-hotel package.',
      'faq.q13':'Can I bring my pet to Penghu?','faq.a13':'Yes, but airlines and ferry operators have different pet rules (advance application, carrier, health certificate), and accommodation must be pet-friendly. Check with us before you travel and we’ll help confirm.',
      'faq.q14':'How do island-hopping ferries work in Penghu?','faq.a14':'To reach Qimei, Wang’an, Jibei and other islands, take a ferry or speedboat from the South Sea or North Sea Visitor Center; schedules vary by season and weather. We arrange the ferries within island-hopping tours so you skip the queue.',
      'faq.q15':'Are flights canceled during typhoons? What then?','faq.a15':'During typhoons or strong waves, flights and ferries may be delayed or canceled. Our itineraries include flexible plans and weather contingencies (e.g. switching to in-depth main-island routes), and we help you handle rebooking to reduce risk.',
      'faq.q16':'What’s the best month to visit Penghu?','faq.a16':'April to September is best: stable weather, warm seas, great for water activities and island hopping. April–June has the fireworks festival with fewer crowds; July–August is busiest and priciest; September–October is still warm with the music & light festival.',
      'faq.q17':'When is Penghu’s peak tourist season?','faq.a17':'Peak season is April–September, especially summer (July–August) and the fireworks festival period. To avoid crowds while keeping good weather, choose April–June or September.',
      'faq.q18':'Can I visit Penghu in winter?','faq.a18':'Yes, but winter (Nov–Feb) is windy and chilly with strong northeasterly monsoons, not suited for water activities, and some shops and ferries close. Winter suits travelers wanting fewer crowds and local food and life.',
      'faq.q19':'When is the Penghu Fireworks Festival?','faq.a19':'The Penghu International Ocean Fireworks Festival is usually held April–June, launched at Guanyinting; it’s one of Penghu’s most iconic events. Exact dates are announced yearly — ask us for fireworks-themed itineraries.',
      'faq.q20':'Is summer in Penghu very hot?','faq.a20':'Summer is sunny and warm, but as an island with constant sea breezes it feels less stifling than the city. Use sun protection, stay hydrated, and schedule water activities for the morning or evening for more comfort.',
      'faq.q21':'Is Penghu very windy?','faq.a21':'Penghu is famous for wind — strongest with the winter northeasterly monsoon; summer winds are gentler and suit all activities. This wind is also why Penghu has unique stone weirs and coral-stone walls.',
      'faq.q22':'Which months can I play in the water in Penghu?','faq.a22':'Roughly May to September the sea is warm and good for snorkeling, SUP and tidal-flat activities. June–August is the prime water season with comfortable temperatures and good visibility.',
      'faq.q23':'When is the rainy season in Penghu?','faq.a23':'Penghu has little overall rainfall; there’s occasional plum rain in May–June and possible afternoon showers or typhoons in summer. Check the forecast before you go — our itineraries also flex with the weather.',
      'faq.q24':'Where are the best sunset spots in Penghu?','faq.a24':'Guanyinting West Rainbow Bridge, the Xiyu Yuwengdao Lighthouse and Waian Fishing Harbor are all famous sunset spots. Penghu’s evening sea-and-sky is the most romantic time — perfect for couples and photos.',
      'faq.q25':'Is Penghu a good place to escape the summer heat?','faq.a25':'Although sunny in summer, Penghu is surrounded by sea with constant breezes and cool evenings. Compared with the city’s humidity, the island’s openness and sea air are relaxing — a nice summer getaway.',
      'faq.q26':'Which area is most convenient to stay in Penghu?','faq.a26':'For a first visit, stay in Magong City — close to the airport, restaurants, night market and harbor, convenient for island hopping and shopping. For sea views or quiet, consider Xiyu or Huxi, but you’ll need your own transport.',
      'faq.q27':'What accommodation options are there in Magong city?','faq.a27':'From budget B&Bs and hostels to star-rated hotels. The city has great amenities and easy evening strolls and late-night snacks, making it most travelers’ first choice. We can match rooms to your budget and group.',
      'faq.q28':'B&B or hotel in Penghu — how to choose?','faq.a28':'For local warmth and value, choose a B&B; for facilities, service and privacy, choose a hotel. Families or those with elderly travelers should pick places with elevators, parking and breakfast.',
      'faq.q29':'How early should I book accommodation in Penghu?','faq.a29':'Rooms are tight in summer and on long weekends, so book 1–2 months ahead. Let us arrange your flight-and-hotel package to save the hassle of comparing and booking yourself.',
      'faq.q30':'Can I stay overnight on the outer islands (Wang’an, Qimei)?','faq.a30':'Yes, the outer islands have B&Bs. Staying overnight lets you experience the islands’ quiet nights, starry skies and morning scenery — a completely different feel from a day trip, so we highly recommend at least one night.',
      'faq.q31':'Roughly how much is accommodation per night in Penghu?','faq.a31':'Prices vary greatly by season. Budget B&B double rooms can start around NT$1,000+ in low season, with hotels higher; peak season costs more. It depends on room type, location and season — our packages include accommodation with transparent pricing.',
      'faq.q32':'Where should families with kids stay?','faq.a32':'Choose city-center hotels or family-room B&Bs with elevators, parking and breakfast, near convenience stores and restaurants — handy for late-night needs or sudden requests from the kids.',
      'faq.q33':'Does Penghu have sea-view accommodation?','faq.a33':'Yes, there are many sea-view B&Bs and hotels along the coast and on the outer islands where you can see the sea and sunset from your room. Sea-view rooms are popular in peak season, so book early — we can help confirm.',
      'faq.q34':'What are Penghu’s must-visit attractions?','faq.a34':'Classics include the Trans-Ocean Bridge, Tongliang Old Banyan, Qibi Mountain “Moses parting the sea,” the Twin-Heart Stone Weir (Qimei), Guanyinting, Xiaomen Whale Cave, Daguoye columnar basalt and Duxing 10th Village. Our tours connect the highlights in one trip.',
      'faq.q35':'Where is the Trans-Ocean Bridge and how do I get there?','faq.a35':'The Penghu Trans-Ocean Bridge links Baisha Island and Xiyu — a Penghu landmark. Self-driving and tours both pass it; the bridgehead is great for photos, near the famous Tongliang banyan and prickly-pear ice.',
      'faq.q36':'What is Qibi Mountain “Moses parting the sea”? Is timing important?','faq.a36':'At low tide, Qibi Mountain reveals an S-shaped gravel path to Chiyu islet, like Moses parting the sea. You must go at the day’s low-tide time or you can’t cross — best to join a tour that tracks the tides.',
      'faq.q37':'Where is the Twin-Heart Stone Weir?','faq.a37':'The most famous Twin-Heart Stone Weir is on Qimei Island — a stone fish trap shaped like two hearts, Penghu’s most iconic photo landmark, reached by island-hopping ferry.',
      'faq.q38':'Is Penghu Tianhou Temple worth visiting?','faq.a38':'Yes. Penghu Tianhou Temple is Taiwan’s oldest Mazu temple — rustic architecture and lively worship, in Magong city, easily combined with a stroll along Central Old Street.',
      'faq.q39':'What is the Tongliang Old Banyan?','faq.a39':'The Tongliang Old Banyan is a banyan tree over 300 years old, its aerial roots spreading into a vast canopy, beside the Trans-Ocean Bridge. Prickly-pear ice stalls often sit beneath it — a classic rest and photo stop.',
      'faq.q40':'Where is the Xiaomen Whale Cave?','faq.a40':'On Xiaomen Islet in Xiyu — a basalt arch formed by sea erosion that looks like a whale’s open mouth from afar; the dramatic coastal geology makes it a must-see on the Xiyu route.',
      'faq.q41':'Where can I see Penghu’s basalt?','faq.a41':'Penghu has world-class basalt landscapes; Daguoye columnar basalt, Chixi Hutou Mountain and Tongpan Islet are all spectacular, with neat columnar joints — a favorite for geology and photography fans.',
      'faq.q42':'Where is Guanyinting and what’s there to do?','faq.a42':'Guanyinting Park is by the sea in Magong city, with the West Rainbow Bridge, a swimming beach and a large lawn — the main venue for sunsets, the fireworks festival and the music & light festival. A lovely evening stroll.',
      'faq.q43':'What is Duxing 10th Village?','faq.a43':'Duxing 10th Village is one of Taiwan’s oldest military dependents’ villages and the former homes of singers Chang Yu-sheng and Pan An-bang. The old houses are now cultural shops and cafés — great for photos and a leisurely walk.',
      'faq.q44':'Is Central Old Street worth a visit?','faq.a44':'Yes. Central Old Street is Magong’s oldest district, gathering the Four-Eyed Well, old houses, souvenirs and snacks; combine it with Tianhou Temple to feel Penghu’s history.',
      'faq.q45':'What lighthouses does Penghu have?','faq.a45':'The Xiyu Yuwengdao Lighthouse (one of Taiwan’s oldest), Qimei Lighthouse and Mudouyu Lighthouse are all distinctive — white towers against blue sky and sea, popular photo landmarks.',
      'faq.q46':'Where are the best Instagram photo spots in Penghu?','faq.a46':'We recommend the Twin-Heart Stone Weir, Daguoye basalt, West Rainbow Bridge, Duxing 10th Village and the outer-island beaches. Blue skies, white sand and gradient seas look great from any angle.',
      'faq.q47':'How do I get to Daguoye columnar basalt?','faq.a47':'It’s in Xiyu, reached by self-driving or tour. At high tide, water pools in front and the row of basalt columns reflects on the surface — dreamlike, a photography hotspot.',
      'faq.q48':'Does Penghu have beaches? Which is the most beautiful?','faq.a48':'Many! Shanshui Beach, Shili Beach, Lintou Park, Jibei Sand Tail and Qimei Yueli Bay are all beautiful, with white sand and crystal-clear water — great for swimming and playing in the sand.',
      'faq.q49':'Is Penghu good for stargazing?','faq.a49':'Absolutely. The outer islands and rural areas have little light pollution and dense star fields; staying overnight on Wang’an or Qimei you can even see the Milky Way. Our overnight island tours often include stargazing time.',
      'faq.q50':'Which outer islands can I visit in Penghu?','faq.a50':'Popular outer islands include Qimei, Wang’an, Jibei, Yuanbei, Niaoyu, Tongpan and the South Four Islands, each with its own character. They’re reached by ferry, and we arrange the routes and ferries for you.',
      'faq.q51':'How do I get to Qimei and how long should I spend?','faq.a51':'Qimei is in Penghu’s South Sea, reached by ferry from Magong. You can do a day trip or stay overnight; must-sees include the Twin-Heart Stone Weir, Little Taiwan, Yueli Bay and Qimei Lighthouse — allow at least half a day to a full day.',
      'faq.q52':'What is special about Wang’an?','faq.a52':'Wang’an is known for green sea turtle conservation, the Huazhai old-house settlement and Tiantai Mountain — relaxed and rich in culture. It’s perfect for travelers wanting to slow down and experience island life, our signature healing route.',
      'faq.q53':'Is Jibei Island worth visiting?','faq.a53':'Yes. Jibei is famous for the long Jibei Sand Tail and water activities — white sand and clear water make it a popular outer island for water sports, banana boats and snorkeling.',
      'faq.q54':'What are Yuanbei Islet and Niaoyu?','faq.a54':'Two small islands in Penghu’s North Sea: Yuanbei has unique basalt columns, while Niaoyu is known for tidal flats and night squid fishing — great for experiencing rustic fishing villages and ecology.',
      'faq.q55':'What are the South Four Islands?','faq.a55':'They are Dongji, Xiji, Dongyuping and Xiyuping, now a national park, with extremely clear water and rich ecology; Xiji’s “Blue Cave” is especially dreamy. This is advanced island hopping for those wanting deep exploration.',
      'faq.q56':'Are Penghu island-hopping day trips recommended?','faq.a56':'Yes. If time is limited, a South Sea (Qimei + Wang’an) or North Sea (Jibei, etc.) day trip covers the highlights in one go. But to truly savor the islands, an overnight stay is more memorable.',
      'faq.q57':'Do I need to stay overnight on the outer islands?','faq.a57':'Not necessarily, but staying overnight lets you experience island nights, starry skies and early mornings, away from day-trip crowds. Our Wang’an two-day-one-night trip is designed for deep experiences and is well loved.',
      'faq.q58':'Where can I see green sea turtles?','faq.a58':'Wang’an in Penghu is an important green sea turtle nesting habitat, with a conservation center to learn about their ecology. While snorkeling in certain waters you may also meet turtles (keep your distance, don’t touch).',
      'faq.q59':'Can I go whale or bird watching in Penghu?','faq.a59':'Some Penghu waters and outer islands (like Maoyu and Niaoyu) are seabird reserves and ecological hotspots; in the right season you can bird-watch and observe wildlife. Whale watching depends on season and sea conditions — ask us to arrange in advance.',
      'faq.q60':'Can I snorkel in Penghu? Where?','faq.a60':'Yes! Penghu’s clear waters are rich in coral and fish; Shanshui, Shili, Jibei and Wang’an are all good snorkeling spots. With guides and equipment provided, even beginners can enter the water with confidence.',
      'faq.q61':'Where can I do SUP in Penghu?','faq.a61':'Penghu’s calm inner bays are ideal for SUP, paddling out to see basalt and sunsets. It’s usually done at dawn or dusk with instructor coaching — a hugely popular activity in recent years.',
      'faq.q62':'Can I do water activities if I can’t swim?','faq.a62':'Yes. For snorkeling and SUP you’ll wear a life jacket with an instructor alongside the whole time, so non-swimmers can take part. Just follow instructions and safety rules and enjoy.',
      'faq.q63':'Does Penghu have kayaking?','faq.a63':'Yes, some waters offer kayaking to enjoy the coastal scenery. Like SUP, you’re provided a life jacket and instructor — great for travelers wanting to try a different ocean activity.',
      'faq.q64':'What is night squid fishing? Is it fun?','faq.a64':'Night squid fishing is Penghu’s summer signature experience — sail out and use light to attract squid, then cook your fresh catch, sweet and delicious. Fun for families and friends, it’s a must-do.',
      'faq.q65':'What is the Penghu tidal-flat experience?','faq.a65':'At low tide you walk onto the tidal flat, guided to learn about starfish, sea cucumbers, shellfish and stone-weir ecology — educational and fun, popular for families and eco-tourism.',
      'faq.q66':'Is Penghu good for diving?','faq.a66':'Yes. Some waters are clear and ecologically rich, suitable for try-dives or advanced dive sites. Diving must be led by a certified instructor and arranged to your condition and certification — discuss with us first.',
      'faq.q67':'Are water activities dangerous? Is there insurance?','faq.a67':'Reputable operators provide certified instructors, safety gear and travel/activity insurance. Choosing a licensed operator and following instructions makes it very safe. Our partners hold the relevant qualifications and coverage.',
      'faq.q68':'Which water activities can children do?','faq.a68':'Tidal-flat exploration, shallow-water snorkeling, sand play and SUP (with a parent) are all suitable, with age and height guidelines and children’s safety gear. Our family tours pick the right activities.',
      'faq.q69':'What should I bring for water activities?','faq.a69':'We suggest a swimsuit, sun protection, towel, change of clothes, dry bag and rash guard. Equipment (goggles, life jacket, etc.) is mostly provided. If worried about sunburn, add a hat and sun sleeves.',
      'faq.q70':'What are Penghu’s must-eat foods?','faq.a70':'Must-eats: squid, fresh seafood, prickly-pear ice, brown sugar cake, peanut crisp, savory biscuits, Penghu loofah and cantaloupe. Fresh seafood and local snacks are a highlight of any Penghu trip.',
      'faq.q71':'How do I eat Penghu’s squid?','faq.a71':'Try squid noodles, blanched squid, sashimi or freshly cooked on a night-fishing trip — sweet and springy. Summer is peak squid season, and pairing it with night squid fishing is unforgettable.',
      'faq.q72':'What is prickly-pear ice? Where to buy it?','faq.a72':'A frozen treat made from Penghu’s specialty prickly-pear fruit — purple-red, sweet-tart and refreshing, a Penghu must-eat. Famous stalls by Tongliang banyan and the Trans-Ocean Bridge make it almost everyone’s grab.',
      'faq.q73':'What is Penghu brown sugar cake?','faq.a73':'Brown sugar cake is Penghu’s most iconic souvenir — soft and chewy with rich brown-sugar aroma, from an Okinawan master’s recipe. Several Magong shops make it fresh — popular to take home and share.',
      'faq.q74':'What seafood do you recommend in Penghu?','faq.a74':'Fresh grouper, lobster, sea urchin, oysters, abalone and various shellfish are all great. Order the day’s catch at a local seafood restaurant — fresh and good value, a flavor you must try in Penghu.',
      'faq.q75':'What souvenirs does Penghu have?','faq.a75':'Popular souvenirs: brown sugar cake, peanut crisp, savory biscuits, scallop sauce, dried fish, sea vegetables and prickly-pear products. Available at Central Old Street and city shops — we leave time to shop at the end of the tour.',
      'faq.q76':'Are Penghu peanut crisp and savory biscuits good?','faq.a76':'Yes! Peanut crisp melts in your mouth and savory biscuits are crisp and moreish — both classic Penghu souvenirs, even better fresh from the oven. Great with tea or as office snacks to share.',
      'faq.q77':'Any night market or city food recommendations in Magong?','faq.a77':'Snacks abound in Magong city and around Beichen Market: seafood porridge, squid noodles, grilled-pork rice and local breakfasts are all worth trying. In the evening you can also stroll and snack — great amenities.',
      'faq.q78':'What’s a local breakfast in Penghu?','faq.a78':'We recommend local breakfast spots’ beef offal soup, anchovy porridge, sesame flatbread and traditional morning bites. Local breakfast stalls often hide delicious surprises — worth getting up early to explore.',
      'faq.q79':'Is it easy for vegetarians to find food in Penghu?','faq.a79':'The city has vegetarian restaurants and buffets, and convenience stores have veggie options, but choices are fewer on the outer islands. Let us know your vegetarian needs in advance and we’ll arrange suitable meals.',
      'faq.q80':'Is Penghu suitable for traveling with children?','faq.a80':'Very much. Beach play, tidal-flat ecology, night squid fishing and DIY experiences delight kids; the short flight with little motion sickness makes it a great family island destination.',
      'faq.q81':'What should I note when traveling with a baby?','faq.a81':'Watch sun protection, hydration and avoiding the midday sun; choose accommodation with elevators and baby facilities. The short flight is easy on babies, but bring formula, diapers and other supplies, and keep the pace relaxed.',
      'faq.q82':'How many days are right for a family trip?','faq.a82':'We suggest 3 days 2 nights or 4 days 3 nights for a relaxed pace that balances water play, ecology and rest. Our family tours deliberately keep flexibility and nap time.',
      'faq.q83':'Are there child-friendly attractions in Penghu?','faq.a83':'Many! The aquarium, ocean ranch, beaches, tidal flats and various DIY activities (brown sugar cake, shell painting) are educational and fun, letting kids learn about the ocean while playing.',
      'faq.q84':'Is Penghu suitable for traveling with elderly family members?','faq.a84':'Yes. Flying is easy and many attractions can be enjoyed from fixed viewpoints; elders love the Trans-Ocean Bridge, temples and seafood. We can arrange a gentle pace with private transfers.',
      'faq.q85':'Will a family itinerary be too tiring?','faq.a85':'No — our family tours deliberately slow the pace with rest and nap time, not cramming in attractions, so adults and kids can relax and avoid too much driving or sun exposure.',
      'faq.q86':'Does Penghu have medical resources? What if my child gets sick?','faq.a86':'Magong city has Penghu Hospital, clinics and pharmacies; medical care is mainly on the main island. The outer islands are more limited, so pack common medicines. If something happens, the guide will help you reach nearby care.',
      'faq.q87':'How many days are ideal for Penghu?','faq.a87':'3 days 2 nights covers the main-island highlights plus one outer island — the most popular length; for more island hopping or depth, 4 days 3 nights is more relaxed. A single-day round trip is rushed; we suggest at least two days.',
      'faq.q88':'Roughly what budget should I prepare for Penghu?','faq.a88':'It varies widely by transport (flight/ferry), accommodation level and activities. Our packages including transport, accommodation and itinerary start from NT$6,000 per person, with transparent pricing and customization to your budget.',
      'faq.q89':'Is independent travel or a tour better for Penghu?','faq.a89':'If you like to arrange freely and don’t mind handling transport and accommodation, go independent; if you want a hassle-free trip with a local guide and island-hopping transfers handled, a tour or semi-guided trip is easier. We offer flexible small-group and custom tours.',
      'faq.q90':'Can a trip run for just two people in Penghu?','faq.a90':'Yes! We have tour packages that run for just two people — friends, couples and partners can set off without forming a group, with high flexibility.',
      'faq.q91':'How do I plan 3 days 2 nights in Penghu?','faq.a91':'A classic plan: Day 1 main-island classics (Trans-Ocean Bridge, basalt, Qibi Mountain); Day 2 island hopping (Qimei or Wang’an); Day 3 city, souvenirs and departure. We’ve designed several 3-day-2-night routes to reference or customize.',
      'faq.q92':'Is Penghu good for company trips?','faq.a92':'Very much! With plenty of activities and strong group interaction, night squid fishing, island hopping, water sports and the music festival all suit company trips. We tailor group itineraries and pricing to your size and budget.',
      'faq.q93':'How do I plan a first trip to Penghu?','faq.a93':'First decide the number of days, season and focus (water play / sights / islands / family), then arrange transport and accommodation. No idea where to start? Tell us your needs and our local team will plan it for you.',
      'faq.q94':'Is a single day enough in Penghu?','faq.a94':'A single day only allows a quick look at part of the main island — a pity. We suggest at least two days and one night to enjoy the outer islands and water activities and fully feel Penghu’s island charm.',
      'faq.q95':'When is the 2026 Penghu Chasing-the-Wind Music & Light Festival?','faq.a95':'The 2026 Penghu Chasing-the-Wind Music & Light Festival takes place at Guanyinting Park, with light shows Sep 12 – Oct 11 and artist performances on Sep 12, 13, 19, 26 and Oct 3. We offer festival-themed itineraries — feel free to ask.',
      'faq.q96':'What should I note when visiting during the festival?','faq.a96':'During the festival (especially performance weekends), flights, ferries and accommodation are in higher demand, so book early. We suggest pairing daytime sights and islands with evening light shows for a fuller trip.',
      'faq.q97':'Does Penghu have convenience stores and ATMs?','faq.a97':'Magong city has convenience stores, ATMs and banks — amenities no different from the main island. The outer islands have fewer, so withdraw cash and prepare supplies before heading over.',
      'faq.q98':'Is reception and internet good in Penghu?','faq.a98':'The main island and major outer islands generally have good 4G/5G reception, and B&Bs and hotels mostly have Wi-Fi. A few remote waters or small islands have weaker signal, which is normal.',
      'faq.q99':'Is card payment convenient in Penghu? Should I bring cash?','faq.a99':'City hotels, restaurants and larger shops mostly accept cards, but traditional markets, food stalls and the outer islands are still cash-based. Bring enough cash and withdraw in the city before island hopping.',
      'faq.q100':'What should I bring to Penghu? Any essentials?','faq.a100':'Essentials: sunscreen, hat, sunglasses, swimsuit, change of clothes, motion-sickness meds, power bank and cash. In summer, sun protection and hydration matter most; in winter, bring a warm windproof jacket.'
    },

    /* ───── 日本語 chrome（問答後續補）───── */
    ja: {
      'faq.heroTitle':'澎湖旅行 よくある質問 100選',
      'faq.heroDesc':'初めての澎湖？行き方、時期、遊び、グルメ、予算は？地元の旅行会社が最もよく聞かれる100の質問にまとめてお答えします。',
      'faq.tocTraffic':'🚢 交通・アクセス','faq.tocSeason':'☀️ 季節・天気','faq.tocStay':'🏨 宿泊','faq.tocSpot':'📸 観光スポット','faq.tocIsland':'🏝️ 離島めぐり','faq.tocWater':'🤿 マリンアクティビティ','faq.tocFood':'🍤 グルメ','faq.tocFamily':'👨‍👩‍👧 ファミリー','faq.tocPlan':'💰 予算・プラン','faq.tocInfo':'🎵 音楽祭・実用情報',
      'faq.catTraffic':'交通・アクセス','faq.catSeason':'ベストシーズンと天気','faq.catStay':'宿泊','faq.catSpot':'観光スポット','faq.catIsland':'離島めぐり','faq.catWater':'マリンアクティビティ','faq.catFood':'グルメ','faq.catFamily':'ファミリー','faq.catPlan':'予算・行程プラン','faq.catInfo':'音楽祭・実用情報',
      'faq.ctaTitle':'まだ疑問がありますか？','faq.ctaDesc':'行程プラン、予算、オーダーメイドのご要望まで、地元澎湖チームが喜んでお答えします。','faq.ctaConsult':'オンライン相談','faq.ctaLine':'LINEで相談','faq.ctaTours':'おすすめツアー'
    },

    /* ───── 한국어 chrome（문답 추후 추가）───── */
    ko: {
      'faq.heroTitle':'펑후 여행 자주 묻는 질문 100선',
      'faq.heroDesc':'펑후가 처음이신가요? 가는 법, 시기, 즐길거리, 먹거리, 예산은? 현지 여행사가 가장 많이 묻는 100가지 질문에 한 번에 답해드립니다.',
      'faq.tocTraffic':'🚢 교통·도착','faq.tocSeason':'☀️ 계절·날씨','faq.tocStay':'🏨 숙박','faq.tocSpot':'📸 명소','faq.tocIsland':'🏝️ 섬 호핑','faq.tocWater':'🤿 해양 액티비티','faq.tocFood':'🍤 먹거리','faq.tocFamily':'👨‍👩‍👧 가족여행','faq.tocPlan':'💰 예산·계획','faq.tocInfo':'🎵 음악축제·실용정보',
      'faq.catTraffic':'교통 및 도착','faq.catSeason':'최적 계절과 날씨','faq.catStay':'숙박','faq.catSpot':'명소','faq.catIsland':'섬 호핑','faq.catWater':'해양 액티비티','faq.catFood':'먹거리','faq.catFamily':'가족여행','faq.catPlan':'예산·일정 계획','faq.catInfo':'음악축제·실용정보',
      'faq.ctaTitle':'더 궁금한 점이 있으신가요?','faq.ctaDesc':'일정 계획, 예산, 맞춤 요청까지 현지 펑후 팀이 기꺼이 도와드립니다.','faq.ctaConsult':'온라인 문의','faq.ctaLine':'LINE 문의','faq.ctaTours':'추천 투어 보기'
    },

    /* ───── 简体中文 chrome（问答后续补）───── */
    'zh-cn': {
      'faq.heroTitle':'澎湖旅游常见问题 100 问',
      'faq.heroDesc':'第一次来澎湖？怎么去、几月去、玩什么、吃什么、花多少？澎湖在地旅行社为你一次解答最常被问到的 100 个问题。',
      'faq.tocTraffic':'🚢 交通抵达','faq.tocSeason':'☀️ 季节天气','faq.tocStay':'🏨 住宿','faq.tocSpot':'📸 景点','faq.tocIsland':'🏝️ 跳岛离岛','faq.tocWater':'🤿 水上活动','faq.tocFood':'🍤 美食','faq.tocFamily':'👨‍👩‍👧 亲子家庭','faq.tocPlan':'💰 预算规划','faq.tocInfo':'🎵 音乐节与实用信息',
      'faq.catTraffic':'交通与抵达','faq.catSeason':'最佳季节与天气','faq.catStay':'住宿','faq.catSpot':'景点','faq.catIsland':'跳岛与离岛','faq.catWater':'水上活动','faq.catFood':'美食','faq.catFamily':'亲子与家庭','faq.catPlan':'预算与行程规划','faq.catInfo':'音乐节与实用信息',
      'faq.ctaTitle':'还有问题没解答到？','faq.ctaDesc':'不论行程规划、预算或客制需求，澎湖在地团队都乐意为你解答。','faq.ctaConsult':'在线咨询','faq.ctaLine':'LINE 咨询','faq.ctaTours':'查看推荐行程'
    }
  };

  ['en','ja','ko','zh-cn'].forEach(l => {
    if (DICT[l]) Object.assign(DICT[l], FAQ[l]);
  });
})();
