# -*- coding: utf-8 -*-
"""澎湖縣水域遊憩公會 2026 會員手冊 → 潮旅官網 tours 資料表 種子腳本
來源：Google Drive 手冊資料夾（32 家業者 DM）。價格為手冊定價，實際以報名確認為準。
執行：python seed_tours.py <DATABASE_PUBLIC_URL>
已存在同名 title 則跳過（可重複執行）。"""
import sys, json, psycopg2

def T(tabs, title, desc, suit, dur, price, prices, hi, inc, notes, i18n, sort):
    return dict(tabs=tabs, title=title, description=desc, suitable_for=suit,
                duration=dur, price_display=price, prices=prices,
                modal_data={"dates": [], "days": [], "highlights": hi,
                            "includes": inc, "notes": notes},
                i18n=i18n, sort_order=sort)

def L(en, ja, ko, cn):
    return {"en": en, "ja": ja, "ko": ko, "zh-cn": cn}

COMMON_NOTE = "本行程為澎湖縣水域遊憩商業同業公會會員產品，由潮旅國際旅行社協助安排與報名；價格為 2026 手冊定價，實際出團時間、成行人數與細節以報名確認為準。遇天候海象不佳，主辦單位保留調整或取消之權利。"

TOURS = [
# ─────────── 本島 main-island ───────────
T(["main-island"], "石斑豐魚季・潮間帶抓魚體驗",
  "在澎湖本島最原始豐富的石斑魚潮間帶，跟著教練體驗百年傳承的漁村抓魚智慧，與野生石斑、錢鰻鬥智鬥勇，結束後現場享用酥炸石斑與澎湖海菜花枝丸麵線。抓不到不收費。由珊瑚礁旅遊提供。",
  "親子 / 生態體驗", "約 3–3.5 小時（配合潮汐）", "NT$ 850 / 人",
  [{"label":"成人","value":"NT$ 850"},{"label":"4–12 歲","value":"NT$ 700"},{"label":"未滿 4 歲","value":"NT$ 100"}],
  ["潮間帶生態探索與石斑魚捕撈","立竿網、抱墩等傳統漁法文化","現炸野生石斑＋海菜花枝丸麵線","提供幼兒浮船，親子可同行"],
  "潮間帶裝備、餐食、保險",
  "行程配合潮汐，每日報到時間不同；漁獲僅帶走大小合適成魚，其餘放回海洋。"+COMMON_NOTE,
  L({"title":"Grouper Catching Intertidal Experience","description":"Catch wild grouper with traditional fishing methods on Penghu's richest intertidal flats, then enjoy freshly fried grouper noodles. No catch, no charge.","duration":"About 3–3.5 hrs (tide-based)","suitable_for":"Families / Eco tour"},
    {"title":"ハタ捕り潮間帯体験","description":"澎湖本島の豊かな潮間帯で、伝統漁法による野生ハタ捕りを体験。捕れたてのハタ料理付き。捕れなければ無料。","duration":"約3〜3.5時間（潮汐に合わせて）","suitable_for":"ファミリー／生態体験"},
    {"title":"그루퍼 잡기 갯벌 체험","description":"펑후 본섬의 갯벌에서 전통 어법으로 야생 그루퍼를 잡고, 갓 튀긴 그루퍼 요리를 맛보는 체험. 못 잡으면 무료.","duration":"약 3~3.5시간(물때 기준)","suitable_for":"가족 / 생태 체험"},
    {"title":"石斑丰鱼季・潮间带抓鱼体验","description":"在澎湖本岛最原始丰富的石斑鱼潮间带，体验百年渔村抓鱼智慧，现场享用酥炸石斑与海菜花枝丸面线。抓不到不收费。","duration":"约 3–3.5 小时（配合潮汐）","suitable_for":"亲子 / 生态体验"}), 101),

T(["main-island"], "夜探龍宮・夜間潮間帶生態導覽",
  "換上頭燈與防滑鞋，跟著教練夜訪鎖港潮間帶，探索珊瑚、海參、海膽、螃蟹、海星等豐富海洋生態，體驗澎湖特殊的「乾式浮潛」。導覽途中撿拾海廢可兌換紀念獎品，下課後品嚐海鮮點心。由海次元提供。",
  "親子 / 夜間生態", "約 3 小時（依潮汐排班）", "NT$ 800 / 人",
  [{"label":"每人","value":"NT$ 800"}],
  ["夜間潮間帶生態導覽＋海洋教育","提供頭燈、防滑鞋、漁網水桶","撿海廢換紀念獎品，寓教於樂","課後海鮮點心，捕獲大型海鮮可現場加菜"],
  "頭燈、防滑鞋、導覽解說、海鮮點心、拍照",
  "需滿 10 人成行；每日場次依潮汐調整。"+COMMON_NOTE,
  L({"title":"Night Intertidal Eco Tour","description":"Explore Suogang's intertidal zone at night with headlamps — corals, sea cucumbers, urchins, crabs and starfish — Penghu's unique 'dry snorkeling', with seafood snacks afterwards.","duration":"About 3 hrs (tide-based)","suitable_for":"Families / Night eco tour"},
    {"title":"夜の潮間帯生態ツアー「夜探龍宮」","description":"ヘッドライトを着けて夜の潮間帯へ。サンゴやナマコ、ウニ、カニなど豊かな海の生き物を観察する澎湖ならではの「乾式シュノーケリング」。終了後は海鮮おやつ付き。","duration":"約3時間（潮汐による）","suitable_for":"ファミリー／ナイトツアー"},
    {"title":"야간 갯벌 생태 투어","description":"헤드랜턴을 쓰고 밤의 갯벌을 탐험하며 산호·해삼·성게·게 등 다양한 해양 생물을 관찰하는 펑후만의 '드라이 스노클링'. 종료 후 해산물 간식 제공.","duration":"약 3시간(물때 기준)","suitable_for":"가족 / 야간 생태"},
    {"title":"夜探龙宫・夜间潮间带生态导览","description":"戴上头灯夜访锁港潮间带，探索珊瑚、海参、海胆、螃蟹等丰富生态，体验澎湖特殊的“干式浮潜”，课后品尝海鲜点心。","duration":"约 3 小时（依潮汐排班）","suitable_for":"亲子 / 夜间生态"}), 102),

T(["main-island"], "風帆・獨木舟・滑水 水上工作坊",
  "澎湖休閒工作坊的夏日水上課程：風浪帆×浪板滑水×獨木舟三合一、SUP＋滑水、SUP＋獨木舟、獨木舟跨島探索無人島等多種組合，含器材與保險，教練帶你 High 翻海平面。",
  "好友 / 進階玩水", "半日（依方案 2–3 小時）", "NT$ 550 起 / 人",
  [{"label":"風帆三合一（風浪帆×滑水×獨木舟）","value":"NT$ 1,800"},{"label":"SUP＋滑水","value":"NT$ 1,350"},{"label":"SUP＋獨木舟","value":"NT$ 950"},{"label":"獨木舟跨島（4 人成行）","value":"NT$ 850"},{"label":"獨木舟體驗","value":"NT$ 550"}],
  ["風浪帆、浪板滑水、獨木舟多元組合","獨木舟跨島探索無人島","上下午多場次，兩人以上成行","含器材使用與保險"],
  "活動器材、保險、沖水間與置物箱",
  "未滿 5 歲幼兒收保險費 100 元；未滿 18 歲需成年家屬陪同。"+COMMON_NOTE,
  L({"title":"Windsurf / Kayak / Waterski Workshop","description":"Summer watersports combos: windsurfing×waterski×kayak 3-in-1, SUP+waterski, SUP+kayak, or kayak island-crossing — gear and insurance included.","duration":"Half day (2–3 hrs)","suitable_for":"Friends / Active watersports"},
    {"title":"ウィンドサーフィン・カヌー・水上スキー体験","description":"ウィンドサーフィン×水上スキー×カヌーの3in1、SUP＋水上スキー、カヌー無人島横断など多彩なコンボ。器材・保険込み。","duration":"半日（2〜3時間）","suitable_for":"友達同士／アクティブ"},
    {"title":"윈드서핑·카약·수상스키 워크숍","description":"윈드서핑×수상스키×카약 3in1, SUP+수상스키, 카약 무인도 횡단 등 다양한 콤보. 장비·보험 포함.","duration":"반나절(2~3시간)","suitable_for":"친구 / 액티브 수상"},
    {"title":"风帆・独木舟・滑水 水上工作坊","description":"风浪帆×浪板滑水×独木舟三合一、SUP＋滑水、独木舟跨岛探索无人岛等多种组合，含器材与保险。","duration":"半日（2–3 小时）","suitable_for":"好友 / 进阶玩水"}), 103),

T(["main-island"], "海洋途徑 Ocean Channel 潛水",
  "從零經驗的體驗潛水到持證潛水員的日間導潛、船潛，海洋途徑潛水中心依你的經驗規劃專屬澎湖海域探索。體驗潛水 12 歲以上即可參加，教練全程帶領安心下水。",
  "潛水入門 / 持證潛水員", "半日（每趟 2 潛）", "NT$ 2,050 起 / 人",
  [{"label":"體驗潛水（12 歲以上）","value":"NT$ 2,800"},{"label":"日間導潛（需潛水證照）","value":"NT$ 2,050"},{"label":"日間船潛（進階證照＋船潛專長）","value":"NT$ 3,600"}],
  ["場次 08:00 / 13:00（體驗另有 10:30、15:30）","依潛水經驗規劃岸潛／船潛地點","專業教練帶領，零經驗也能參加體驗潛水"],
  "潛水裝備與教練帶領（裝備租賃另計；依方案）",
  "潛水後 12 小時內（多支氣瓶 18 小時）不得搭機；心血管疾病、氣喘、懷孕等不適合參加。"+COMMON_NOTE,
  L({"title":"Ocean Channel Diving","description":"From zero-experience intro dives to guided shore dives and boat dives for certified divers — customized Penghu underwater exploration.","duration":"Half day (2 dives)","suitable_for":"Beginners / Certified divers"},
    {"title":"海洋途徑ダイビング","description":"未経験OKの体験ダイビングから、ライセンス保持者向けガイド付き岸潜・ボートダイビングまで、経験に合わせた澎湖の海の探検。","duration":"半日（2ダイブ）","suitable_for":"初心者／ライセンス保持者"},
    {"title":"오션 채널 다이빙","description":"무경험 체험 다이빙부터 자격증 소지자를 위한 가이드 비치·보트 다이빙까지, 경험에 맞춘 펑후 바다 탐험.","duration":"반나절(2다이브)","suitable_for":"입문자 / 자격증 다이버"},
    {"title":"海洋途径 Ocean Channel 潜水","description":"从零经验体验潜水到持证潜水员的日间导潜、船潜，依你的经验规划专属澎湖海域探索。","duration":"半日（每趟 2 潜）","suitable_for":"潜水入门 / 持证潜水员"}), 104),

T(["main-island"], "海底漫步 SEA WALK",
  "不會游泳也能在深海餵魚！戴上供氣頭盔漫步海底，或選擇浮潛探訪海底郵筒、競速 SUP、漁人潮間帶與星光夜遊。天氣好加碼送跳水體驗，多種套餐自由搭配。",
  "親子 / 不會游泳", "單項約 1.5–2 小時；套餐約 3 小時", "NT$ 300 起 / 人",
  [{"label":"海底漫步","value":"NT$ 1,250"},{"label":"浮潛（海底郵筒）","value":"NT$ 800"},{"label":"競速 SUP","value":"NT$ 1,000"},{"label":"漁人潮間帶","value":"NT$ 850"},{"label":"星光夜遊","value":"NT$ 300"},{"label":"漫步＋浮潛套餐","value":"NT$ 1,500"},{"label":"漫步＋SUP 套餐","value":"NT$ 2,000"}],
  ["戴供氣頭盔海底漫步，不會游泳也 OK","浮潛帶到海底郵筒巡遊","SUP 有日出、夕陽場次","星光夜遊：涼傘文化＋沙灘幽靈蟹＋三〇高地賞星"],
  "裝備、教練、保險、點心",
  "請提早 10 分鐘報到，逾時不候。"+COMMON_NOTE,
  L({"title":"SEA WALK Underwater Walking","description":"Walk on the seabed with an air-supplied helmet and feed fish — no swimming needed. Also snorkeling to the undersea mailbox, SUP, fisherman's intertidal tour and starlight night tour.","duration":"1.5–3 hrs by package","suitable_for":"Families / Non-swimmers"},
    {"title":"シーウォーク（海底散歩）","description":"給気ヘルメットを被って海底をお散歩、泳げなくても魚に餌やりOK。海底ポストへのシュノーケリングやSUP、星空ナイトツアーも。","duration":"パッケージにより1.5〜3時間","suitable_for":"ファミリー／泳げない方"},
    {"title":"씨워크 해저 산책","description":"급기 헬멧을 쓰고 해저를 걸으며 물고기에게 먹이주기 — 수영 못해도 OK. 해저 우체통 스노클링, SUP, 별빛 나이트 투어도 선택 가능.","duration":"패키지별 1.5~3시간","suitable_for":"가족 / 수영 초보"},
    {"title":"海底漫步 SEA WALK","description":"戴上供气头盔漫步海底，不会游泳也能在深海喂鱼；另有海底邮筒浮潜、竞速 SUP、渔人潮间带与星光夜游。","duration":"单项约 1.5–2 小时；套餐约 3 小时","suitable_for":"亲子 / 不会游泳"}), 105),

T(["main-island"], "菠蘿水上樂園（盛夏娛樂）",
  "海上充氣樂園狂歡今夏：彈跳包、高台跳水、溜滑梯、海上泳池、水上飄、造型泳圈、SUP 立式划槳一票暢玩，早上、下午各一場。由盛夏娛樂提供。",
  "親子 / 好友團體", "約 3 小時（08:30–11:30／14:00–17:00）", "NT$ 1,490 / 人",
  [{"label":"每人","value":"NT$ 1,490"},{"label":"7–12 歲","value":"半價 NT$ 745"},{"label":"6 歲以下","value":"NT$ 100（保險費）"}],
  ["海上充氣樂園：彈跳包、溜滑梯、高台跳水","海上泳池、水上飄、造型泳圈","含 SUP 立式划槳體驗"],
  "樂園設施使用、SUP、保險",
  "請提前 15 分鐘集合。"+COMMON_NOTE,
  L({"title":"Pineapple Floating Water Park","description":"Inflatable sea park fun: trampoline, high-dive platform, slides, sea pool, floating mats, tube rings and SUP — one ticket plays all.","duration":"About 3 hrs","suitable_for":"Families / Groups"},
    {"title":"パイナップル海上ウォーターパーク","description":"海上インフレータブルパークで夏を満喫：トランポリン、飛び込み台、スライダー、海上プール、SUPまで1チケットで遊び放題。","duration":"約3時間","suitable_for":"ファミリー／グループ"},
    {"title":"파인애플 해상 워터파크","description":"해상 에어바운스 파크: 트램펄린, 다이빙대, 슬라이드, 해상 수영장, SUP까지 티켓 한 장으로 무제한.","duration":"약 3시간","suitable_for":"가족 / 단체"},
    {"title":"菠萝水上乐园（盛夏娱乐）","description":"海上充气乐园：弹跳包、高台跳水、溜滑梯、海上泳池、水上飘、SUP 一票畅玩，早上、下午各一场。","duration":"约 3 小时","suitable_for":"亲子 / 好友团体"}), 106),

T(["main-island"], "小門漂浮鯨魚・獨木舟／SUP／帆船",
  "在小門鯨魚洞旁的海域，划獨木舟或 SUP 迎日出、追夕陽、環遊小島，或搭帆船從海上視角欣賞鯨魚洞。日出場含海上早餐，一般場含飲料點心。由一本商號「漂浮鯨魚」提供。",
  "情侶 / 攝影 / 日出夕陽", "1.5–3 小時（多場次）", "NT$ 1,000 起 / 人",
  [{"label":"獨木舟遊島（16:30–19:00）","value":"NT$ 1,300"},{"label":"獨木舟日出＋海上早餐","value":"NT$ 1,500"},{"label":"獨木舟繞島（15:00–19:00）","value":"NT$ 1,700"},{"label":"SUP 上午／下午場","value":"NT$ 1,300"},{"label":"SUP 日出＋早餐","value":"NT$ 1,500"},{"label":"SUP 夕陽＋點心","value":"NT$ 1,700"},{"label":"帆船體驗（海上鯨魚洞）","value":"NT$ 1,000"},{"label":"帆船夕陽場（含 SUP＋海上浮毯）","value":"NT$ 1,800"}],
  ["海上視角欣賞小門鯨魚洞","日出、夕陽、遊島多種場次","日間航次 2 人成行，開放現場報名","兒童價適用 6–12 歲"],
  "裝備、教練、保險；依場次含早餐或飲料點心",
  "5 歲以下幼兒不建議上舟。"+COMMON_NOTE,
  L({"title":"Whale Cave Kayak / SUP / Sailboat","description":"Paddle a kayak or SUP at sunrise or sunset beside Xiaomen Whale Cave, or view the sea arch from a sailboat. Sunrise sessions include breakfast at sea.","duration":"1.5–3 hrs (multiple sessions)","suitable_for":"Couples / Photography"},
    {"title":"小門クジラ洞カヌー／SUP／ヨット","description":"小門鯨魚洞のそばでカヌーやSUPに乗って日の出・夕日・島巡り。ヨットで海からクジラ洞を眺めるコースも。日の出便は海上朝食付き。","duration":"1.5〜3時間（複数便）","suitable_for":"カップル／フォトジェニック"},
    {"title":"샤오먼 고래동굴 카약/SUP/세일보트","description":"샤오먼 고래동굴 옆 바다에서 카약·SUP로 일출과 일몰, 섬 일주를 즐기거나 세일보트로 바다에서 고래동굴 감상. 일출편은 해상 조식 포함.","duration":"1.5~3시간(다양한 세션)","suitable_for":"커플 / 사진 명소"},
    {"title":"小门漂浮鲸鱼・独木舟/SUP/帆船","description":"在小门鲸鱼洞旁划独木舟或 SUP 迎日出、追夕阳，或搭帆船从海上欣赏鲸鱼洞。日出场含海上早餐。","duration":"1.5–3 小时（多场次）","suitable_for":"情侣 / 摄影 / 日出夕阳"}), 107),

T(["main-island"], "波賽頓海洋運動俱樂部",
  "體驗潛水、海底郵筒浮潛、嵵裡沙灘 SUP、寬板滑水，花火節期間更有獨家夜划 SUP／龍舟板海上賞花火。不會游泳也能跟著教練潛入湛藍大海。",
  "入門玩水 / 賞花火", "單項 1.5–3 小時", "NT$ 650 起 / 人",
  [{"label":"體驗潛水","value":"NT$ 2,400"},{"label":"浮潛（海底郵筒）","value":"NT$ 650"},{"label":"SUP（嵵裡沙灘夕陽場）","value":"NT$ 1,000"},{"label":"寬板滑水","value":"NT$ 1,500"},{"label":"夜划 SUP 賞花火（2 人 1 板）","value":"NT$ 900"},{"label":"夜划龍舟板賞花火（8 人 1 板）","value":"NT$ 900"}],
  ["體驗潛水零經驗可參加","浮潛寄出海底郵筒明信片","花火節限定：夜划海上賞花火","嵵裡沙灘平緩安全，適合 SUP 初學者"],
  "裝備、教練、保險",
  "夜划花火場次 20:00–21:30，限花火節期間。"+COMMON_NOTE,
  L({"title":"Poseidon Marine Sports Club","description":"Intro scuba, undersea-mailbox snorkeling, SUP at Shili Beach and wakeboarding — plus exclusive night-paddle SUP to watch fireworks at sea during the festival.","duration":"1.5–3 hrs per activity","suitable_for":"Beginners / Fireworks"},
    {"title":"ポセイドン海洋クラブ","description":"体験ダイビング、海底ポストシュノーケリング、嵵裡ビーチSUP、ウェイクボード。花火祭期間は海上から花火を眺めるナイトSUPも。","duration":"各1.5〜3時間","suitable_for":"初心者／花火鑑賞"},
    {"title":"포세이돈 해양 스포츠 클럽","description":"체험 다이빙, 해저 우체통 스노클링, 스리 해변 SUP, 웨이크보드. 불꽃축제 기간엔 바다 위에서 불꽃을 감상하는 나이트 SUP도.","duration":"종목당 1.5~3시간","suitable_for":"입문자 / 불꽃 감상"},
    {"title":"波赛顿海洋运动俱乐部","description":"体验潜水、海底邮筒浮潜、嵵里沙滩 SUP、宽板滑水，花火节期间更有独家夜划 SUP 海上赏花火。","duration":"单项 1.5–3 小时","suitable_for":"入门玩水 / 赏花火"}), 108),

T(["main-island"], "空中散步・拖曳傘體驗（海玩子）",
  "搭乘快艇升空 60 米，無憂無慮俯瞰澎湖群島的海天一色。夏季限定（4–9 月），每日四個航班。由海玩子提供。",
  "情侶 / 挑戰系", "單趟體驗（每日 09:00／11:00／14:00／16:00）", "NT$ 1,600 / 人",
  [{"label":"每人","value":"NT$ 1,600"}],
  ["60 米高空俯瞰澎湖島嶼","快艇出海＋拖曳傘飛行","夏季限定 4–9 月"],
  "快艇、拖曳傘裝備、保險",
  COMMON_NOTE,
  L({"title":"Parasailing over Penghu","description":"Soar 60 meters above the sea behind a speedboat for a bird's-eye view of the Penghu islands. Summer only (Apr–Sep), four flights daily.","duration":"Single flight","suitable_for":"Couples / Thrill seekers"},
    {"title":"パラセーリング「空中散歩」","description":"スピードボートに引かれて上空60mへ。澎湖の島々を一望する夏限定（4〜9月）の絶景体験。","duration":"1フライト","suitable_for":"カップル／スリル好き"},
    {"title":"펑후 패러세일링","description":"쾌속정에 이끌려 60m 상공으로! 펑후 섬들을 한눈에 내려다보는 여름 한정(4~9월) 체험.","duration":"1회 비행","suitable_for":"커플 / 스릴 추구"},
    {"title":"空中散步・拖曳伞体验（海玩子）","description":"搭快艇升空 60 米俯瞰澎湖群岛，夏季限定（4–9 月），每日四个航班。","duration":"单趟体验","suitable_for":"情侣 / 挑战系"}), 109),

T(["main-island"], "南方四島珊瑚森林自由潛水（海玩子）",
  "前進珊瑚覆蓋率達 60% 的東嶼坪海域，在國際優良等級的珊瑚森林自由潛水。每週二、五 09:00 出發、16:00 回程，約 8 小時，八人成行。含面鏡、呼吸管、救生衣、飲用水與中餐。",
  "自潛玩家 / 進階", "約 8 小時（週二、週五出發）", "NT$ 3,000 / 人",
  [{"label":"每人","value":"NT$ 3,000"}],
  ["東嶼坪珊瑚覆蓋率達 60%，國際優良等級","南方四島國家公園海域","八人成行，人數未達船長協助湊團"],
  "面鏡、呼吸管、救生衣、飲用水、中餐",
  "航程較遠請自備暈船藥；愛護海洋請勿使用防曬油。"+COMMON_NOTE,
  L({"title":"South Penghu Coral Forest Freediving","description":"Freedive the coral forests of Dongyuping — 60% coral coverage, international-grade reefs in South Penghu Marine National Park. Tue & Fri, about 8 hours.","duration":"About 8 hrs (Tue/Fri)","suitable_for":"Freedivers / Advanced"},
    {"title":"南方四島サンゴの森フリーダイビング","description":"サンゴ被度60%の東嶼坪海域でフリーダイビング。南方四島国家公園の世界級のサンゴ礁へ。毎週火・金曜、約8時間。","duration":"約8時間（火・金）","suitable_for":"フリーダイバー／上級者"},
    {"title":"남방사도 산호숲 프리다이빙","description":"산호 피복률 60%의 둥위핑 해역에서 프리다이빙. 남방사도 해양국가공원의 세계급 산호초. 매주 화·금, 약 8시간.","duration":"약 8시간(화/금)","suitable_for":"프리다이버 / 상급자"},
    {"title":"南方四岛珊瑚森林自由潜水（海玩子）","description":"前进珊瑚覆盖率达 60% 的东屿坪海域自由潜水，每周二、五出发，约 8 小时，八人成行。","duration":"约 8 小时（周二、周五）","suitable_for":"自潜玩家 / 进阶"}), 110),

T(["main-island"], "日日潛水 GOODAY DIVE",
  "小班制潛水店：浮潛導覽、PADI 體驗潛水（1 對 2）、SSI/PADI 開放水域潛水員證照課程與進階課程，場次彈性，適合想認真學潛水的旅人。",
  "潛水入門 / 考證", "半日～3 天（依課程）", "NT$ 800 起 / 人",
  [{"label":"浮潛導覽（1 對 6）","value":"NT$ 800"},{"label":"浮潛 6–8 歲","value":"NT$ 1,600"},{"label":"體驗潛水（1 對 2）","value":"NT$ 2,700"},{"label":"OW 開放水域證照課","value":"NT$ 13,800"},{"label":"AOW 進階課程","value":"NT$ 11,000"}],
  ["場次 08:00／10:00／13:00／15:00","體驗潛水 12 歲以上、教練 1 對 2","證照課含教材、裝備與簽證"],
  "裝備、教練；證照課含教材與簽證費",
  "潛水後 12–18 小時內不得搭機。"+COMMON_NOTE,
  L({"title":"GOODAY DIVE","description":"Small-group dive shop: guided snorkeling, PADI intro dives (1:2) and SSI/PADI Open Water & advanced certification courses.","duration":"Half day to 3 days","suitable_for":"Beginners / Certification"},
    {"title":"日日潜水 GOODAY DIVE","description":"少人数制ダイブショップ。シュノーケリング、体験ダイビング（1対2）、SSI/PADIオープンウォーター講習など。","duration":"半日〜3日","suitable_for":"初心者／ライセンス取得"},
    {"title":"구데이 다이브 GOODAY DIVE","description":"소수정예 다이브숍: 스노클링, 체험 다이빙(1:2), SSI/PADI 오픈워터·어드밴스 자격 과정.","duration":"반나절~3일","suitable_for":"입문 / 자격증"},
    {"title":"日日潜水 GOODAY DIVE","description":"小班制潜水店：浮潜导览、体验潜水（1 对 2）、SSI/PADI 开放水域证照课程与进阶课程。","duration":"半日～3 天","suitable_for":"潜水入门 / 考证"}), 111),

T(["main-island"], "陽光阿有 浮潛・體驗潛水・SUP・潮間帶",
  "小班制客製服務：專業浮潛探訪海底郵筒、體驗潛水（1 對 2）、SUP 立式划槳與潮間帶「澎湖人的冰箱」導覽，也有浮潛＋潛水、浮潛＋SUP 的一日組合優惠。",
  "親子 / 小班客製", "單項 1.5–2.5 小時", "NT$ 500 起 / 人",
  [{"label":"專業浮潛／海底郵筒","value":"NT$ 900"},{"label":"體驗潛水（1 對 2）","value":"NT$ 2,800"},{"label":"體驗潛水（1 對 1）","value":"NT$ 3,400"},{"label":"SUP 充氣板單人","value":"NT$ 1,500"},{"label":"SUP 雙人一板","value":"每人 NT$ 1,000"},{"label":"潮間帶探險","value":"NT$ 500"},{"label":"浮潛＋體驗潛水組合","value":"NT$ 3,500"},{"label":"浮潛＋SUP 組合","value":"NT$ 1,700"}],
  ["浮潛場次 08:30／09:30／13:30／14:30","體驗潛水 14–55 歲、含整套裝備","潮間帶 15:30–17:00，滿 10 人成行","全程拍照留念"],
  "保險、整套裝備、拍照、點心",
  "請於活動前 10 分鐘抵達集合點。"+COMMON_NOTE,
  L({"title":"Sunny U Snorkel / Dive / SUP / Intertidal","description":"Small-group services: snorkeling to the undersea mailbox, intro dives (1:2), SUP, intertidal eco tours, plus combo packages.","duration":"1.5–2.5 hrs per activity","suitable_for":"Families / Small groups"},
    {"title":"陽光阿有 シュノーケル・体験ダイビング・SUP","description":"少人数制：海底ポストシュノーケリング、体験ダイビング（1対2）、SUP、潮間帯ツアーとお得なセットプランも。","duration":"各1.5〜2.5時間","suitable_for":"ファミリー／少人数"},
    {"title":"써니아유 스노클·다이빙·SUP·갯벌","description":"소그룹 맞춤: 해저 우체통 스노클링, 체험 다이빙(1:2), SUP, 갯벌 투어와 콤보 패키지.","duration":"종목당 1.5~2.5시간","suitable_for":"가족 / 소그룹"},
    {"title":"阳光阿有 浮潜・体验潜水・SUP・潮间带","description":"小班制客制服务：海底邮筒浮潜、体验潜水（1 对 2）、SUP 与潮间带导览，另有一日组合优惠。","duration":"单项 1.5–2.5 小时","suitable_for":"亲子 / 小班客制"}), 112),

T(["main-island"], "魚加貓 YOGA × SUP 海上瑜伽",
  "在山水沙灘把瑜伽墊換成 SUP 板：SUP 立式划槳教學、海上瑜伽與沙灘瑜伽派對，日出場 4:30、夕陽場 16:00，教練全程側拍還有免費空拍服務。",
  "女生旅行 / 攝影 / 身心放鬆", "約 2–2.5 小時", "NT$ 800 起 / 人",
  [{"label":"SUP 教學（1 人 1 板）","value":"NT$ 1,500"},{"label":"SUP 教學（2 人 1 板）","value":"每人 NT$ 1,250"},{"label":"SUP 海上瑜伽（預約價）","value":"NT$ 2,000"},{"label":"沙灘瑜伽派對","value":"NT$ 800"}],
  ["日出場 4:30／夕陽場 16:00","教練全程側拍＋免費空拍","SUP 瑜伽限一人一板，2 人成團"],
  "立槳裝備、教學、水域險、拍照",
  "活動可能因潮汐氣候調整時間或取消。"+COMMON_NOTE,
  L({"title":"YOGA × SUP on the Sea","description":"Swap your yoga mat for a SUP board at Shanshui Beach: SUP lessons, floating SUP yoga and beach yoga parties at sunrise or sunset, with free drone photos.","duration":"About 2–2.5 hrs","suitable_for":"Wellness / Photography"},
    {"title":"魚加貓 YOGA×SUP 海上ヨガ","description":"山水ビーチでヨガマットをSUPボードに。SUPレッスン、海上ヨガ、ビーチヨガパーティー。日の出・夕日便、ドローン撮影無料。","duration":"約2〜2.5時間","suitable_for":"ウェルネス／フォト"},
    {"title":"요가×SUP 해상 요가","description":"산수이 해변에서 요가매트 대신 SUP 보드를! SUP 강습, 해상 요가, 비치 요가 파티. 일출·일몰 세션, 드론 촬영 무료.","duration":"약 2~2.5시간","suitable_for":"웰니스 / 사진"},
    {"title":"鱼加猫 YOGA × SUP 海上瑜伽","description":"在山水沙滩体验 SUP 教学、海上瑜伽与沙滩瑜伽派对，日出场 4:30、夕阳场 16:00，含免费空拍。","duration":"约 2–2.5 小时","suitable_for":"女生旅行 / 摄影 / 放松"}), 113),

T(["main-island"], "隘海人 OCEANERS 海上平台半日遊",
  "搭船前往隘門沙灘外的海中央休息站——360 度全景海上平台，玩 SUP 或透明獨木舟；也可探索神祕無人島香爐嶼＋秘境浮潛，或參加含早餐的日出團，在 SUP 板上迎接澎湖的第一道曙光。",
  "情侶 / 秘境探索", "半日（多場次）", "NT$ 1,000 起 / 人",
  [{"label":"SUP 或透明獨木舟（二選一）","value":"NT$ 1,000"},{"label":"香爐嶼無人島＋秘境浮潛","value":"NT$ 1,950"},{"label":"香爐嶼 7–12 歲","value":"NT$ 1,000"},{"label":"日出團（含早餐）","value":"NT$ 1,800"}],
  ["360 度全景海上平台專屬座位","無人島香爐嶼登島＋秘境浮潛","日出團：SUP 板上看第一道曙光＋早餐","場次 09:00–11:00／13:00–15:00／15:30–17:30"],
  "裝備（全新咬嘴、面鏡、救生衣）、教練、專業浮潛教學",
  "6 歲以下免費、另收保險費 200 元；未達 5 人成團將提前一天通知改期。"+COMMON_NOTE,
  L({"title":"OCEANERS Sea Platform Half-day","description":"Boat out to a 360° panoramic sea platform off Aimen Beach for SUP or clear kayak; explore uninhabited Xianglu Islet with hidden-spot snorkeling, or join the sunrise tour with breakfast.","duration":"Half day (multiple sessions)","suitable_for":"Couples / Hidden spots"},
    {"title":"OCEANERS 海上プラットフォーム半日ツアー","description":"隘門ビーチ沖の360度パノラマ海上プラットフォームでSUPや透明カヌー。無人島・香炉嶼上陸＋秘境シュノーケリング、朝食付きサンライズツアーも。","duration":"半日（複数便）","suitable_for":"カップル／秘境"},
    {"title":"오셔너스 해상 플랫폼 반나절","description":"아이먼 해변 앞바다의 360도 파노라마 해상 플랫폼에서 SUP·투명 카약을 즐기고, 무인도 샹루위 상륙+비경 스노클링, 조식 포함 일출 투어도 선택 가능.","duration":"반나절(다양한 세션)","suitable_for":"커플 / 비경 탐험"},
    {"title":"隘海人 OCEANERS 海上平台半日游","description":"搭船前往隘门沙滩外的 360 度全景海上平台，玩 SUP 或透明独木舟；可探索无人岛香炉屿＋秘境浮潜，或参加含早餐的日出团。","duration":"半日（多场次）","suitable_for":"情侣 / 秘境探索"}), 114),

T(["main-island"], "興仁潛水 體驗潛水・PADI 證照班",
  "馬公烏崁的在地潛水中心：體驗潛水含裝備、教練與海底照片，前進海底郵筒潛點；想更進一步可報名 PADI 初級潛水證照班（三天課程，3–11 月開課）。",
  "潛水入門 / 考證", "體驗 2 小時；證照班 3 天", "NT$ 2,800 起 / 人",
  [{"label":"體驗潛水（含海底照片）","value":"NT$ 2,800"},{"label":"PADI OW 證照班（1 人報名）","value":"NT$ 15,800"},{"label":"PADI OW（2 人同行）","value":"每人 NT$ 15,300"},{"label":"PADI OW（3 人同行）","value":"每人 NT$ 14,500"}],
  ["體驗潛水梯次 8:00／10:00／14:00／16:00","含裝備、海底照片與教練","證照班含 PADI 教材、氣瓶裝備與簽證"],
  "裝備、教練、海底照片；證照班含教材與簽證",
  "體驗潛水適合 12–50 歲；潛水後 12 小時內不得搭機。"+COMMON_NOTE,
  L({"title":"Xingren Diving — Intro Dive & PADI Course","description":"Local dive center at Wukan: intro dives with gear, instructor and underwater photos, plus 3-day PADI Open Water certification courses (Mar–Nov).","duration":"2 hrs / 3-day course","suitable_for":"Beginners / Certification"},
    {"title":"興仁ダイビング 体験＆PADI講習","description":"馬公・烏崁のダイビングセンター。器材・水中写真付き体験ダイビングと、3日間のPADIオープンウォーター講習（3〜11月開講）。","duration":"体験2時間／講習3日","suitable_for":"初心者／ライセンス"},
    {"title":"싱런 다이빙 체험·PADI 과정","description":"마공 우칸의 로컬 다이빙 센터: 장비·수중사진 포함 체험 다이빙과 3일 PADI 오픈워터 자격 과정(3~11월).","duration":"체험 2시간 / 과정 3일","suitable_for":"입문 / 자격증"},
    {"title":"兴仁潜水 体验潜水・PADI 证照班","description":"体验潜水含装备、教练与海底照片；PADI 初级潜水证照班三天课程，3–11 月开课。","duration":"体验 2 小时；证照班 3 天","suitable_for":"潜水入门 / 考证"}), 115),

T(["main-island"], "和慶海洋牧場・夜釣小管",
  "從馬公搭船 5 分鐘到海上牧場平台：餵食觸摸魟魚、餵釣海鱺、逗趣花枝，碳烤牡蠣與海鮮粥品嚐；夏夜還能出海垂釣野生小管，或在花火節搭配海上賞花火＋釣小管。",
  "親子 / 海上餵食體驗", "約 2 小時", "NT$ 550 起 / 人",
  [{"label":"海洋牧場（12 歲以上）","value":"NT$ 600"},{"label":"海洋牧場 3–12 歲","value":"NT$ 350"},{"label":"看煙火＋釣小管","value":"NT$ 650"},{"label":"垂釣野生小管（夜間）","value":"NT$ 550"},{"label":"3 歲以下（抱票）","value":"NT$ 50"}],
  ["餵食觸摸魟魚、海鱺、花枝","碳烤牡蠣＋海鮮粥","日間多航班；夜釣 19:00／21:00","花火節限定：海上賞花火＋釣小管"],
  "船票、平台活動、餐點（碳烤牡蠣、海鮮粥）",
  "航程約 5 分鐘不易暈船。"+COMMON_NOTE,
  L({"title":"Heqing Ocean Ranch & Night Squid Fishing","description":"A 5-minute boat ride to a sea ranch platform: touch rays, feed cobia and cuttlefish, enjoy grilled oysters and seafood congee; night squid fishing and fireworks cruises in season.","duration":"About 2 hrs","suitable_for":"Families / Feeding experience"},
    {"title":"和慶海洋牧場・夜のイカ釣り","description":"船で5分の海上牧場プラットフォームへ。エイやスギに餌やり、牡蠣の炭火焼きと海鮮粥食べ放題。夏の夜はイカ釣りや花火クルーズも。","duration":"約2時間","suitable_for":"ファミリー／餌やり体験"},
    {"title":"허칭 해양목장·야간 오징어 낚시","description":"배로 5분 거리 해상 목장에서 가오리 만지기, 물고기 먹이주기, 굴 숯불구이와 해물죽까지. 여름밤엔 오징어 낚시와 불꽃 크루즈도.","duration":"약 2시간","suitable_for":"가족 / 먹이주기 체험"},
    {"title":"和庆海洋牧场・夜钓小管","description":"搭船 5 分钟到海上牧场平台：喂食触摸魟鱼、海鲡、花枝，碳烤牡蛎与海鲜粥；夏夜可垂钓野生小管或海上赏花火。","duration":"约 2 小时","suitable_for":"亲子 / 海上喂食体验"}), 116),

T(["main-island"], "星光海洋牧場",
  "從菜園遊客中心搭船 5 分鐘到箱網平台，觸摸魟魚、餵釣海鱺、逗趣花枝、戲弄河豚，海景第一排炭烤牡蠣與海鮮粥吃到飽；秋冬另有海陸遊專案與敲魚乾 DIY。",
  "親子 / 全年可玩", "約 2 小時（含船程來回）", "NT$ 550 / 人",
  [{"label":"大人（12 歲以上）","value":"NT$ 550"},{"label":"小孩 3–12 歲","value":"NT$ 300"},{"label":"3 歲以下","value":"NT$ 50"}],
  ["觸摸魟魚、餵釣海鱺、逗趣花枝","炭烤牡蠣＋海鮮粥吃到飽","營業 08:00–17:00 多航班","秋冬限定海陸遊專案、澎湖魚乾 DIY（+100 元）"],
  "船票、平台體驗、碳烤牡蠣與海鮮粥吃到飽",
  "船程僅 5–6 分鐘，不易暈船。"+COMMON_NOTE,
  L({"title":"Starlight Ocean Ranch","description":"5-minute boat ride to a fish-farm platform: touch rays, feed cobia, tease cuttlefish and puffers, with all-you-can-eat grilled oysters and seafood congee by the sea.","duration":"About 2 hrs","suitable_for":"Families / All year"},
    {"title":"星光海洋牧場","description":"船で5分の生簀プラットフォームでエイに触れ、魚に餌やり。海景一等席で牡蠣の炭火焼き＆海鮮粥食べ放題。秋冬はDIYプランも。","duration":"約2時間","suitable_for":"ファミリー／通年"},
    {"title":"싱광 해양목장","description":"배로 5분, 가두리 플랫폼에서 가오리 만지기와 먹이주기, 바다 전망 굴 숯불구이·해물죽 무한리필. 가을·겨울 DIY 프로그램도.","duration":"약 2시간","suitable_for":"가족 / 사계절"},
    {"title":"星光海洋牧场","description":"搭船 5 分钟到箱网平台，触摸魟鱼、喂钓海鲡、逗趣花枝，炭烤牡蛎与海鲜粥吃到饱；秋冬另有海陆游专案与鱼干 DIY。","duration":"约 2 小时","suitable_for":"亲子 / 全年可玩"}), 117),

T(["main-island"], "春帆遊艇 包船海上時光",
  "包下整艘雙體遊艇出海：海上溜滑梯、SUP、透明獨木舟、KTV、啤酒飲料暢飲，前進「澎爾地夫」浪蕩洲沙洲；夜晚另有花火包船，20:00 出發海上賞花火配炸雞與 KTV。",
  "團體包船 / 派對", "約 3.5 小時（10:00／15:00）；花火場 2 小時", "包船 NT$ 38,800 起",
  [{"label":"包船海上冒險（3.5 小時）","value":"NT$ 52,400"},{"label":"花火包船（20:00–22:00，最多 30 位）","value":"NT$ 38,800"}],
  ["雙體遊艇包船，海上溜滑梯＋SUP＋透明獨木舟","登上澎爾地夫「浪蕩洲」沙洲","KTV＋啤酒飲料暢飲","花火包船含炸雞與啤酒暢飲"],
  "船資、水上器材、KTV、酒水飲料暢飲",
  COMMON_NOTE,
  L({"title":"Chunfan Yacht Private Charter","description":"Charter a whole catamaran: sea slide, SUP, clear kayak, karaoke and free-flow beer, landing on the 'Penghu Maldives' sandbar; fireworks-night charters too.","duration":"About 3.5 hrs / 2-hr fireworks","suitable_for":"Group charter / Party"},
    {"title":"春帆ヨット貸切クルーズ","description":"カタマランを貸し切って海上スライダー、SUP、透明カヌー、カラオケ、ビール飲み放題。「澎湖のモルディブ」浪蕩洲にも上陸。花火ナイト貸切も。","duration":"約3.5時間／花火2時間","suitable_for":"グループ貸切／パーティー"},
    {"title":"춘판 요트 전세 크루즈","description":"카타마란 통째 전세: 해상 슬라이드, SUP, 투명 카약, 노래방, 맥주 무제한. '펑후 몰디브' 모래섬 상륙과 불꽃놀이 전세도.","duration":"약 3.5시간 / 불꽃 2시간","suitable_for":"단체 전세 / 파티"},
    {"title":"春帆游艇 包船海上时光","description":"包下双体游艇：海上溜滑梯、SUP、透明独木舟、KTV、啤酒畅饮，登上“澎尔地夫”浪荡洲；另有花火包船。","duration":"约 3.5 小时；花火场 2 小时","suitable_for":"团体包船 / 派对"}), 118),

T(["main-island"], "蠔野人 低調奢華 MINI TOUR（包車＋包船）",
  "專屬司機從馬公市區包車環島觀光，行至西嶼大菓葉碼頭換包船返航，中途停留海上玩水、賞夕陽，贈船上點心與酒水飲料暢飲。海陸雙享一次滿足，8–9 小時的奢華小團。",
  "小團包制 / 海陸雙享", "約 8–9 小時", "3 人小團 NT$ 10,000 起",
  [{"label":"3 人小團（轎車）","value":"NT$ 10,000"},{"label":"4–8 人團（Benz Vito／Staria）","value":"NT$ 17,000"}],
  ["包車環島＋包船返航海陸雙享","海上玩水、賞夕陽","含司機、船長及船員、船上點心酒水暢飲"],
  "司機、船長船員、船上點心、酒水飲料暢飲",
  COMMON_NOTE,
  L({"title":"Oyster Bros Luxury MINI TOUR (Car + Boat)","description":"Private-driver island tour from Magong, then board a private boat at Daguoye pier to cruise home — swim stops, sunset at sea, snacks and free-flow drinks. 8–9 hours of low-key luxury.","duration":"About 8–9 hrs","suitable_for":"Private mini group"},
    {"title":"蠔野人 贅沢MINI TOUR（車＋船チャーター）","description":"専属ドライバーの島内観光後、大菓葉埠頭からチャーター船で海上遊泳＆夕日クルーズ。軽食・ドリンク飲み放題付きの8〜9時間。","duration":"約8〜9時間","suitable_for":"プライベート少人数"},
    {"title":"오이스터 브로스 럭셔리 미니투어(차량+보트)","description":"전용 차량 섬 일주 후 다궈예 부두에서 전세 보트로 해상 물놀이와 선셋 크루즈. 간식·음료 무제한, 8~9시간의 프라이빗 투어.","duration":"약 8~9시간","suitable_for":"프라이빗 소그룹"},
    {"title":"蚝野人 低调奢华 MINI TOUR（包车＋包船）","description":"专属司机包车环岛，西屿大菓叶码头换包船返航，海上玩水、赏夕阳，赠点心与酒水畅饮，8–9 小时海陆双享。","duration":"约 8–9 小时","suitable_for":"小团包制 / 海陆双享"}), 119),

# ─────────── 北海 north-sea ───────────
T(["north-sea"], "蠔野人 漂流北方仙境（目斗嶼＋吉貝沙尾）",
  "精緻小船 6 人成團穿越跨海大橋，尋找澎湖最北端的目斗嶼與東海仙境澎澎灘，踏上最美麗海灣吉貝沙尾。含海鮮風味餐、自家養殖現蒸牡蠣與酒水飲料，贈吉貝島上機車與 SUP 體驗。",
  "跳島 / 小團精緻", "一日遊", "NT$ 2,800 / 人",
  [{"label":"每人","value":"NT$ 2,800"},{"label":"包船","value":"NT$ 23,000 起"}],
  ["澎湖最北目斗嶼＋吉貝沙尾","精緻小船 6 人成團、上限 12 位","海鮮風味餐＋現蒸牡蠣＋酒水飲料","贈吉貝機車兩人一台＋SUP 體驗"],
  "救生衣、面鏡呼吸管（全新咬嘴）、毛巾、餐食、機車",
  COMMON_NOTE,
  L({"title":"Northern Paradise Drift (Mudou & Jibei)","description":"Small-boat tour (min 6, max 12) to Penghu's northernmost Mudou Islet and Jibei Sand Tail, with seafood meal, steamed oysters, drinks, scooter on Jibei and SUP.","duration":"Full day","suitable_for":"Island hopping / Small group"},
    {"title":"北方仙境ツアー（目斗嶼＋吉貝サンドテール）","description":"最少6名の小型ボートで澎湖最北端の目斗嶼と吉貝サンドテールへ。海鮮料理・蒸し牡蠣・ドリンク付き、吉貝島バイクとSUP体験も。","duration":"1日","suitable_for":"アイランドホッピング"},
    {"title":"북방 선경 투어(무더우+지베이)","description":"소형 보트(6인 출발)로 펑후 최북단 무더우섬과 지베이 모래꼬리 해변으로. 해산물 식사·찐 굴·음료 포함, 지베이 스쿠터와 SUP 체험 증정.","duration":"1일","suitable_for":"섬 호핑 / 소그룹"},
    {"title":"蚝野人 漂流北方仙境（目斗屿＋吉贝沙尾）","description":"精致小船 6 人成团，前往澎湖最北目斗屿与吉贝沙尾，含海鲜风味餐、现蒸牡蛎与酒水，赠吉贝机车与 SUP 体验。","duration":"一日游","suitable_for":"跳岛 / 小团精致"}), 201),

T(["north-sea"], "沛無限 北海漫遊（吉貝）",
  "座落澎湖吉貝的 Infinity & Fantastic 沛無限，乘遊艇探索北海秘境：北方四島巡航＋目斗吉貝登島、吉貝＋目斗嶼半日，或水上樂園＋釣魚／SUP／獨木舟／浮潛／水上摩托車的水上活動組合，行程後可至海上餐酒館享用主廚海鮮大餐。",
  "北海跳島 / 質感旅行", "3–6 小時（依方案）", "NT$ 1,480 起 / 人",
  [{"label":"A：北方四島巡航＋目斗吉貝登島（6HR）","value":"NT$ 2,200"},{"label":"B：吉貝＋目斗嶼（4HR）","value":"NT$ 1,480"},{"label":"C：水上活動組合（3HR）","value":"NT$ 2,200"}],
  ["目斗嶼燈塔登島＋吉貝旅遊","觀賞鐵砧海鷗／天然海蝕洞","A 方案含釣魚體驗＋餐酒館餐券＋島上機車","C 方案：水上樂園＋SUP＋獨木舟＋浮潛＋水上摩托車"],
  "船資、保險；依方案含機車、餐券與水上活動",
  "碼頭：赤崁、吉貝。"+COMMON_NOTE,
  L({"title":"Infinity & Fantastic North Sea Cruise (Jibei)","description":"Yacht tours from Jibei: North Isles cruise with Mudou & Jibei landings, or a watersports combo (sea park, SUP, kayak, snorkeling, jet ski), finished with a chef's seafood feast at the sea bistro.","duration":"3–6 hrs by plan","suitable_for":"North sea island hopping"},
    {"title":"沛無限 北海クルーズ（吉貝）","description":"吉貝発ヨットツアー。北方四島巡航＋目斗・吉貝上陸、または海上パーク・SUP・カヌー・ジェットスキーのマリンコンボ。海上レストランのシーフードも。","duration":"プランにより3〜6時間","suitable_for":"北海アイランドホッピング"},
    {"title":"인피니티&판타스틱 북해 크루즈(지베이)","description":"지베이 출발 요트 투어: 북방 4개 섬 순항+무더우·지베이 상륙, 또는 해상 파크·SUP·카약·제트스키 콤보. 해상 레스토랑 셰프 해산물 요리도.","duration":"플랜별 3~6시간","suitable_for":"북해 섬 호핑"},
    {"title":"沛无限 北海漫游（吉贝）","description":"乘游艇探索北海：北方四岛巡航＋目斗吉贝登岛、吉贝半日游，或水上乐园＋SUP＋浮潜＋水上摩托车组合。","duration":"3–6 小时（依方案）","suitable_for":"北海跳岛 / 质感旅行"}), 202),

T(["north-sea","south-sea"], "JESSIE 澎湖私囊潛行（天堂島／南方四島）",
  "潛水攝影團隊帶路的小眾路線：北海「天堂島」目斗嶼＋吉貝沙尾貝殼沙灘 SUP、玫瑰珊瑚浮潛與海蝕洞燕鷗群；或南方四島國家公園薰衣草珊瑚雙潛點自由潛水＋西吉藍洞。含海陸空攝影服務，團體包船、併團 6 位開團。",
  "攝影 / 自潛 / 秘境", "一日遊", "線上詢價",
  [{"label":"北海天堂島／南方四島行程","value":"線上詢價"}],
  ["目斗嶼＋吉貝沙尾 SUP 與玫瑰珊瑚浮潛","南方四島薰衣草珊瑚、西吉藍洞","海、陸、空專業攝影服務","併團 6 位開團"],
  "裝備、教練、攝影服務",
  COMMON_NOTE,
  L({"title":"JESSIE Private Dive Tours (Paradise Isles / South Penghu)","description":"Small-group routes led by a dive-photo team: Mudou 'paradise island' with shell-beach SUP and rose coral snorkeling, or South Penghu lavender-coral freediving with Blue Cave cruising. Photo service included.","duration":"Full day","suitable_for":"Photography / Freediving"},
    {"title":"JESSIE プライベート潜行（天国の島／南方四島）","description":"水中撮影チームが案内する少人数ルート。目斗嶼と吉貝の貝殻ビーチSUP・バラサンゴシュノーケリング、または南方四島ラベンダーサンゴのフリーダイビング＋西吉ブルーケーブ。撮影サービス付き。","duration":"1日","suitable_for":"フォト／フリーダイビング"},
    {"title":"제시 프라이빗 다이브 투어(천국의 섬/남방사도)","description":"다이빙 촬영팀이 이끄는 소수 루트: 무더우 '천국의 섬' SUP와 장미 산호 스노클링, 또는 남방사도 라벤더 산호 프리다이빙+시지 블루케이브. 촬영 서비스 포함.","duration":"1일","suitable_for":"사진 / 프리다이빙"},
    {"title":"JESSIE 澎湖私囊潜行（天堂岛/南方四岛）","description":"潜水摄影团队带路：北海目斗屿＋吉贝沙尾 SUP 与玫瑰珊瑚浮潜，或南方四岛薰衣草珊瑚自由潜水＋西吉蓝洞，含海陆空摄影服务。","duration":"一日游","suitable_for":"摄影 / 自潜 / 秘境"}), 203),

# ─────────── 東海 east-sea ───────────
T(["east-sea"], "鉅航 東海一日遊／樂活包",
  "從早玩到日落的東海經典：快艇巡航賞玄武岩與海燕鷗、鳥嶼潮間帶生態導覽（立竿網抓魚、石滬浮潛餵魚）、澎澎灘八合一水上活動或海釣；另有海上平台半日與樂活包組合。",
  "家庭 / 東海經典", "半日～一日", "NT$ 1,000 起 / 人",
  [{"label":"A：東海巡航一日遊","value":"NT$ 1,450"},{"label":"C：東海樂活包一日遊","value":"NT$ 1,450"},{"label":"B：踏浪半日遊","value":"NT$ 1,000"},{"label":"海上樂園平台行程","value":"NT$ 1,350"}],
  ["東海巡航賞玄武岩＋海燕鷗","鳥嶼潮間帶：立竿網、抱墩、石滬浮潛餵魚","澎澎灘水上活動：水上摩托車、香蕉船、SUP 等八合一","兩層樓海景平台：溜滑梯、高空跳水、海上盪鞦韆"],
  "船資、活動器材、保險",
  "如遇風浪過大，巡航改為員貝登島導覽。"+COMMON_NOTE,
  L({"title":"Juhang East Sea Day Tour","description":"Classic East Sea day: speedboat cruise past basalt isles and terns, Niaoyu intertidal eco tour, then eight-in-one watersports at Pengpeng Beach or sea-platform fun.","duration":"Half to full day","suitable_for":"Families / East Sea classic"},
    {"title":"鉅航 東海1日ツアー","description":"玄武岩とアジサシを巡るクルーズ、鳥嶼の潮間帯ツアー、澎澎灘の8種マリンスポーツや海上プラットフォームまで、朝から夕方まで東海満喫。","duration":"半日〜1日","suitable_for":"ファミリー／東海定番"},
    {"title":"쥐항 동해 원데이 투어","description":"현무암 섬과 제비갈매기 크루즈, 냐오위 갯벌 투어, 펑펑탄 8종 수상 액티비티 또는 해상 플랫폼까지 아침부터 저녁까지 동해 만끽.","duration":"반나절~1일","suitable_for":"가족 / 동해 클래식"},
    {"title":"钜航 东海一日游/乐活包","description":"快艇巡航赏玄武岩与海燕鸥、鸟屿潮间带生态导览、澎澎滩八合一水上活动；另有海上平台半日与乐活包组合。","duration":"半日～一日","suitable_for":"家庭 / 东海经典"}), 301),

T(["east-sea"], "鉅航 龍蝦島抓龍蝦一日遊",
  "登陸東海最夯的龍蝦島，探索潮間帶生態、體驗趣味抓龍蝦，專人現場料理新鮮龍蝦泡麵（抓不到一樣送）；搭配東海巡航與澎澎灘水上活動，從早上出港一路玩到下午。",
  "嚐鮮 / 團體同樂", "一日遊", "NT$ 3,000 / 人",
  [{"label":"每人（優惠價）","value":"NT$ 3,000"}],
  ["登陸龍蝦島＋趣味抓龍蝦","專人料理龍蝦泡麵（抓不到也送）","東海巡航賞玄武岩、海燕鷗","澎澎灘多樣水上活動"],
  "船資、活動、龍蝦泡麵餐、保險",
  COMMON_NOTE,
  L({"title":"Lobster Island Catching Day Tour","description":"Land on the East Sea's hottest Lobster Island, catch lobsters in the intertidal zone and feast on lobster noodles (guaranteed even if you catch none), plus cruising and watersports.","duration":"Full day","suitable_for":"Foodies / Groups"},
    {"title":"ロブスター島 伊勢海老捕り1日ツアー","description":"話題のロブスター島に上陸して伊勢海老捕り体験。捕れなくてもロブスターラーメン付き。クルーズとマリンスポーツも。","duration":"1日","suitable_for":"グルメ／グループ"},
    {"title":"랍스터섬 랍스터 잡기 원데이","description":"동해의 핫플 랍스터섬에 상륙해 랍스터 잡기 체험, 못 잡아도 랍스터 라면 제공. 크루즈와 수상 액티비티까지.","duration":"1일","suitable_for":"미식 / 단체"},
    {"title":"钜航 龙虾岛抓龙虾一日游","description":"登陆龙虾岛体验抓龙虾，专人现场料理龙虾泡面（抓不到一样送），搭配东海巡航与水上活动。","duration":"一日游","suitable_for":"尝鲜 / 团体同乐"}), 302),

T(["east-sea"], "新來發 東海一日遊",
  "海島探險七大亮點：員貝文房四寶、鳥嶼大峽谷玄武岩、小白沙嶼、雞善嶼與錠鉤嶼、澎澎灘登島、燕鷗生態觀察，加上珊瑚礁玩水樂園八種玩法與船長漁家菜，員貝小荷蘭村巡禮。",
  "深度東海 / 家庭", "約 7.5 小時（09:00–16:30）", "NT$ 1,600 / 人",
  [{"label":"12 歲以上","value":"NT$ 1,600"},{"label":"3–11 歲","value":"NT$ 1,000"},{"label":"未滿 3 歲（保險）","value":"NT$ 100"}],
  ["員貝文房四寶＋鳥嶼大峽谷玄武岩","雞善嶼、錠鉤嶼海蝕景觀保護區","澎澎灘登島＋燕鷗生態觀察","浮潛、SUP、海上魔毯、獨木舟等八種玩水","船長漁家菜＋員貝島環島巡禮"],
  "船資、水上活動、漁家午餐、保險",
  "集合：白沙鄉岐頭遊客中心，08:50 報到。"+COMMON_NOTE,
  L({"title":"Xinlaifa East Sea Day Tour","description":"Seven island highlights — Yuanbei rock formations, Niaoyu basalt canyon, tern watching, Pengpeng Beach landing — plus eight watersports at the coral reef playground and the captain's home-style seafood.","duration":"About 7.5 hrs","suitable_for":"In-depth East Sea / Families"},
    {"title":"新來發 東海1日ツアー","description":"員貝の奇岩、鳥嶼の玄武岩大峡谷、アジサシ観察、澎澎灘上陸など7大ハイライトに、サンゴ礁での8種の水遊びと船長の漁師料理。","duration":"約7.5時間","suitable_for":"東海満喫／ファミリー"},
    {"title":"신라이파 동해 원데이 투어","description":"위안베이 기암, 냐오위 현무암 대협곡, 제비갈매기 관찰, 펑펑탄 상륙 등 7대 하이라이트에 산호초 8종 물놀이와 선장의 어부 요리까지.","duration":"약 7.5시간","suitable_for":"동해 심층 / 가족"},
    {"title":"新来发 东海一日游","description":"员贝文房四宝、鸟屿大峡谷、小白沙屿、鸡善屿与锭钩屿、澎澎滩登岛、燕鸥观察，加珊瑚礁玩水乐园八种玩法与船长渔家菜。","duration":"约 7.5 小时","suitable_for":"深度东海 / 家庭"}), 303),

T(["east-sea"], "新來發 夜釣小管體驗（包船）",
  "夏季限定（5–9 月盛產期）：從岐頭碼頭出海，在滿天星斗下體驗集魚燈夜釣小管與漁夫傳統下網捕撈示範，現場享用金瓜米粉或芋頭海鮮粥、牡蠣與小管麵線、小管生魚片，釣獲全數帶走。",
  "夏季限定 / 團體包船", "約 3 小時（18:00–21:00）", "包船制・線上詢價",
  [{"label":"包船","value":"線上詢價"}],
  ["集魚燈夜釣小管＋漁夫下網示範","主食金瓜米粉或芋頭海鮮粥","兩人一斤牡蠣＋一夜乾＋小管麵線／生魚片","釣獲與撈獲全數帶走或現場出售"],
  "船資、釣具、海鮮晚宴、保險",
  "集合：白沙鄉岐頭遊客中心。"+COMMON_NOTE,
  L({"title":"Night Squid Fishing Charter","description":"Summer-only (May–Sep) night fishing under the stars: catch neritic squid by fish-luring lights, watch traditional net fishing, and feast on a seafood dinner aboard. Keep all your catch.","duration":"About 3 hrs (18:00–21:00)","suitable_for":"Summer / Group charter"},
    {"title":"夜のイカ釣り体験（貸切）","description":"夏限定（5〜9月）。集魚灯でヤリイカ釣りと伝統の網漁実演、船上で海鮮ディナー。釣果はすべてお持ち帰りOK。","duration":"約3時間（18:00〜21:00）","suitable_for":"夏限定／グループ貸切"},
    {"title":"야간 오징어 낚시(전세)","description":"여름 한정(5~9월). 집어등 아래 오징어 낚시와 전통 그물질 시연, 선상 해산물 만찬까지. 잡은 것은 모두 가져갈 수 있어요.","duration":"약 3시간(18:00~21:00)","suitable_for":"여름 한정 / 단체 전세"},
    {"title":"新来发 夜钓小管体验（包船）","description":"夏季限定：满天星斗下体验集鱼灯夜钓小管与渔夫传统下网示范，现场享用海鲜晚宴，钓获全数带走。","duration":"约 3 小时（18:00–21:00）","suitable_for":"夏季限定 / 团体包船"}), 304),

T(["east-sea"], "銀海遊艇 東海一日遊",
  "全新優惠行程：無人島賞上千隻海鳥、八項水上活動組合（透明獨木舟、SUP、超大型溜滑梯、高空跳水、香蕉船、海戰車、搖擺飛船）、員貝後山與雞善嶼錠鉤嶼巡航、玄武岩故鄉與海底火山口小富士山。",
  "東海全覽 / 家庭", "約 7 小時", "NT$ 700 起 / 人",
  [{"label":"A：東海超值一日遊","value":"NT$ 1,400"},{"label":"B：遨遊東海（4 小時，50 人成行）","value":"NT$ 700"},{"label":"C：海田夢幻（4 小時）","value":"NT$ 700"}],
  ["無人島賞上千隻海鳥飛舞","八合一水上活動或海釣二選一","小富士山、大峽谷柱狀玄武岩","C 方案：浮潛餵魚秀＋海瓜子區＋抱墩捉魚","專人拍照，FB 免費下載"],
  "船資、水上活動、保險",
  "集合：岐頭港。"+COMMON_NOTE,
  L({"title":"Yinhai Yacht East Sea Day Tour","description":"Thousands of seabirds at an uninhabited isle, eight-in-one watersports, basalt canyon and 'Little Fuji' undersea volcano cruising — with a snorkel fish-feeding show option.","duration":"About 7 hrs","suitable_for":"East Sea highlights / Families"},
    {"title":"銀海遊艇 東海1日ツアー","description":"無人島で数千羽の海鳥、8種のマリンスポーツ、玄武岩の峡谷と「小富士山」海底火山クルーズ。餌やりシュノーケリングのコースも。","duration":"約7時間","suitable_for":"東海ハイライト／ファミリー"},
    {"title":"인하이 요트 동해 원데이","description":"무인도의 수천 마리 바닷새, 8종 수상 액티비티, 현무암 협곡과 '리틀 후지' 해저 화산 크루즈. 물고기 먹이주기 스노클링 코스도.","duration":"약 7시간","suitable_for":"동해 하이라이트 / 가족"},
    {"title":"银海游艇 东海一日游","description":"无人岛赏上千只海鸟、八项水上活动、员贝后山与鸡善屿巡航、玄武岩故乡与海底火山口小富士山。","duration":"约 7 小时","suitable_for":"东海全览 / 家庭"}), 305),

T(["east-sea"], "東方之美 員貝生態休閒一日遊",
  "一票玩到底的員貝小島慢旅：在地人帶路島上導覽、抱墩網魚、海田踏浪尋寶、浮潛餵魚、海洋獨木舟與 SUP、風味團餐八菜一湯、戶外卡拉 OK 歡唱，再搭遊艇巡航員貝後山、鳥嶼與澎澎灘賞燕鷗。",
  "漁村慢活 / 家庭", "約 7 小時（依潮汐）", "NT$ 1,600 / 人",
  [{"label":"每人","value":"NT$ 1,600"},{"label":"3–6 歲","value":"NT$ 1,320"},{"label":"未滿 3 歲（保險）","value":"NT$ 200"}],
  ["員貝島在地人導覽＋小荷蘭村","抱墩網魚、海田踏浪、浮潛餵魚","海洋獨木舟＋SUP 立槳","風味團餐八菜一湯＋免費卡拉 OK","遊艇巡航：石筆石硯、鳥嶼、澎澎灘、賞燕鷗"],
  "東海船票、活動、午餐、三重保險",
  "適用 2026/4/1–9/30。"+COMMON_NOTE,
  L({"title":"Yuanbei Eco Leisure Day Tour","description":"Slow island life on Yuanbei: local-guided village walk, traditional fish trapping, intertidal treasure hunt, snorkel fish feeding, kayak & SUP, an eight-dish home feast and cruise past basalt wonders.","duration":"About 7 hrs (tide-based)","suitable_for":"Fishing village life / Families"},
    {"title":"員貝生態休閒1日ツアー","description":"地元ガイドの島歩き、伝統の抱墩漁、潮間帯宝探し、餌やりシュノーケリング、カヌー＆SUP、8品の郷土料理とカラオケ、玄武岩クルーズまで。","duration":"約7時間（潮汐による）","suitable_for":"漁村スローライフ／ファミリー"},
    {"title":"위안베이 생태 힐링 원데이","description":"현지인 가이드 섬 산책, 전통 고기잡이, 갯벌 보물찾기, 먹이주기 스노클링, 카약&SUP, 8첩 향토 밥상과 노래방, 현무암 크루즈까지.","duration":"약 7시간(물때 기준)","suitable_for":"어촌 슬로우 라이프 / 가족"},
    {"title":"东方之美 员贝生态休闲一日游","description":"一票玩到底：岛上导览、抱墩网鱼、海田踏浪、浮潜喂鱼、独木舟与 SUP、风味团餐与卡拉 OK，再巡航赏燕鸥。","duration":"约 7 小时（依潮汐）","suitable_for":"渔村慢活 / 家庭"}), 306),

T(["east-sea"], "戀夏遊艇 東海行程",
  "戀夏船隊的東海全系列：精選／超值一日遊（玄武岩巡航、周家潮間帶、鳥嶼登島午餐、海上戲水）、休閒半日、星空之旅龍蝦海鮮泡麵晚餐加贈夜釣小管，以及夕陽之約「尋龍趣」抓龍蝦嚐龍蝦沙西米。",
  "東海多方案 / 星空夜遊", "3–8 小時（依方案）", "NT$ 800 起 / 人",
  [{"label":"A：精選東海一日","value":"NT$ 1,250"},{"label":"B：超值東海一日","value":"NT$ 1,450"},{"label":"C：休閒半日","value":"NT$ 800"},{"label":"D：星空之旅（17:00–20:00）","value":"NT$ 2,000"},{"label":"夕陽之約・尋龍趣（14:00–20:00）","value":"NT$ 2,800"}],
  ["世界遺產級玄武岩巡航＋賞燕鷗","周家潮間帶抱墩、敲石蚵","鳥嶼登島＋漁村風味餐","星空之旅：龍蝦泡麵＋澎澎灘夕陽＋夜釣小管","尋龍趣：教練潛水抓龍蝦＋龍蝦沙西米"],
  "船資、活動、餐食（依方案）、200 萬船險與水域險",
  "集合：岐頭遊客中心戀夏櫃檯。"+COMMON_NOTE,
  L({"title":"Love Summer Yacht East Sea Tours","description":"Full East Sea lineup: basalt cruises, intertidal fun, Niaoyu island lunch, sea play — plus a starlight lobster-noodle dinner cruise with squid fishing, and a sunset lobster-catching trip with sashimi.","duration":"3–8 hrs by plan","suitable_for":"Multiple plans / Night cruise"},
    {"title":"戀夏ヨット 東海ツアー","description":"玄武岩クルーズ、潮間帯遊び、鳥嶼上陸ランチ、星空ロブスターラーメンクルーズ＋イカ釣り、夕日のロブスター捕り＆刺身まで多彩なプラン。","duration":"プランにより3〜8時間","suitable_for":"多彩プラン／ナイトクルーズ"},
    {"title":"롄샤 요트 동해 투어","description":"현무암 크루즈, 갯벌 체험, 냐오위 상륙 점심, 별빛 랍스터 라면 크루즈+오징어 낚시, 선셋 랍스터 잡기와 사시미까지 다양한 플랜.","duration":"플랜별 3~8시간","suitable_for":"다양한 플랜 / 나이트 크루즈"},
    {"title":"恋夏游艇 东海行程","description":"精选/超值一日游、休闲半日、星空之旅龙虾泡面晚餐加赠夜钓小管，以及夕阳“寻龙趣”抓龙虾尝龙虾刺身。","duration":"3–8 小时（依方案）","suitable_for":"东海多方案 / 星空夜游"}), 307),

T(["east-sea"], "員貝樂營 貝貝島一日遊",
  "員貝樂營×貝貝社區發展協會的生態教育之旅：絕美小島巡航賞燕鷗、潮間帶尋寶或手捲釣魚、登島享用豪華龍蝦麵疙瘩午餐、小管一日乾 DIY，玩水方案再加海上盪鞦韆、溜滑梯、SUP 浮潛。",
  "親子食魚教育 / 東海", "3–7 小時（依方案）", "NT$ 800 起 / 人",
  [{"label":"a：貝貝耍廢一日遊（不玩水）","value":"NT$ 1,250"},{"label":"b：悠遊員貝一日遊（玩水）","value":"NT$ 1,600"},{"label":"c：員貝海牧之旅（3 小時）","value":"NT$ 800"},{"label":"d：貝貝海牧玩水之旅（5 小時）","value":"NT$ 1,400"},{"label":"未滿 3 歲","value":"NT$ 100"}],
  ["員貝後山文房四寶＋澎澎灘巡航賞燕鷗","潮間帶抱墩、敲石蚵或老船長秘點手捲釣魚","豪華龍蝦麵疙瘩午餐＋特色凍飲","食魚教育：小管一日乾 DIY","海牧方案：無鉤拉竿釣花枝＋牡蠣海鮮粥吃到飽"],
  "船資、活動、午餐／海鮮粥、200 萬船險與水域險",
  "集合：岐頭遊客中心員貝樂營櫃台。"+COMMON_NOTE,
  L({"title":"Beibei Island Day Tour (Yuanbei Camp)","description":"Eco-education island trip: cruise past tern colonies, intertidal treasure hunts or hand-line fishing, a luxurious lobster gnocchi lunch, DIY dried squid, plus sea swings, slides and SUP on water plans.","duration":"3–7 hrs by plan","suitable_for":"Family food education"},
    {"title":"員貝樂營 貝貝島1日ツアー","description":"生態教育の島旅：アジサシクルーズ、潮間帯宝探しや手釣り、ロブスターすいとんランチ、イカの一夜干しDIY。水遊びプランは海上ブランコやSUPも。","duration":"プランにより3〜7時間","suitable_for":"親子・食育"},
    {"title":"베이베이섬 원데이(위안베이 캠프)","description":"생태 교육 여행: 제비갈매기 크루즈, 갯벌 보물찾기·손낚시, 랍스터 수제비 점심, 오징어 반건조 DIY. 물놀이 플랜은 해상 그네와 SUP까지.","duration":"플랜별 3~7시간","suitable_for":"가족 식육 교육"},
    {"title":"员贝乐营 贝贝岛一日游","description":"生态教育之旅：小岛巡航赏燕鸥、潮间带寻宝或手卷钓鱼、豪华龙虾面疙瘩午餐、小管一日干 DIY，玩水方案加海上荡秋千与 SUP。","duration":"3–7 小时（依方案）","suitable_for":"亲子食鱼教育 / 东海"}), 308),

# ─────────── 南海 south-sea ───────────
T(["south-sea"], "珊瑚礁旅遊 忘憂島一日遊",
  "南海秘境忘憂島：登陸頭巾嶼探訪無人島潮池、珊瑚礁海域秘境浮潛與珊瑚復育區、專屬海上度假平台 360 度海景享用海鮮套餐，海上溜滑梯、寬板滑水等水上遊樂一次滿足，每組贈遊程紀念照。",
  "無人島 / 浮潛", "約 9 小時", "NT$ 3,900 / 人",
  [{"label":"成人","value":"NT$ 3,900"},{"label":"未滿 4 歲（不含餐）","value":"NT$ 1,000"}],
  ["登陸無人島頭巾嶼＋潮池探索","珊瑚礁秘境浮潛＋珊瑚復育區","專屬海上平台：海鮮套餐＋網美露台","海上溜滑梯、寬板滑水、搖擺飛船","每組贈遊程紀念照 5 張"],
  "船資、浮潛裝備教學、海上平台、海鮮午餐、保險",
  "08:00 南海碼頭報到；行程依潮汐調整。"+COMMON_NOTE,
  L({"title":"Wangyou Island Day Tour","description":"South Sea hidden gem: land on uninhabited Toujin Islet, snorkel secret coral reefs and restoration zones, and enjoy a seafood set on a private sea platform with slides and wakeboarding.","duration":"About 9 hrs","suitable_for":"Uninhabited island / Snorkeling"},
    {"title":"忘憂島1日ツアー","description":"南海の秘境へ。無人島・頭巾嶼上陸、サンゴ礁秘境シュノーケリング、専用海上プラットフォームでのシーフードセットと海上スライダー。","duration":"約9時間","suitable_for":"無人島／シュノーケリング"},
    {"title":"왕유섬 원데이 투어","description":"남해의 비경: 무인도 터우진위 상륙, 산호초 비경 스노클링, 전용 해상 플랫폼 해산물 세트와 해상 슬라이드·웨이크보드까지.","duration":"약 9시간","suitable_for":"무인도 / 스노클링"},
    {"title":"珊瑚礁旅游 忘忧岛一日游","description":"登陆头巾屿探访无人岛潮池、珊瑚礁秘境浮潜、专属海上平台 360 度海景海鲜套餐与海上溜滑梯等水上游乐。","duration":"约 9 小时","suitable_for":"无人岛 / 浮潜"}), 401),

T(["south-sea"], "忘憂島生態夜泊・無人島露營",
  "沉浸在一座私人的無人島：秘境浮潛、潮間帶尋寶、SUP 追尋少年 Pi 的夜光砂、海上星空晚餐與沙灘營火，免裝備入住兩人帳篷，清晨在無人島迎接海景日出。一泊二食的奢華野營。",
  "無人島過夜 / 特殊體驗", "13:30 至隔日 08:30（一泊二食）", "NT$ 5,800 / 人",
  [{"label":"每人","value":"NT$ 5,800"}],
  ["免裝備無人島過夜（兩人帳、睡墊、毛毯）","忘憂島秘境浮潛＋珊瑚復育區","夜間浮潛或 SUP 探訪夜光砂","星空晚餐＋沙灘營火＋無人島日出","海上平台供電、盥洗、廚房"],
  "露營裝備、一泊二食、浮潛裝備、保險",
  "8–22 人併團成行；不開放 4 歲以下參加。"+COMMON_NOTE,
  L({"title":"Wangyou Island Overnight Camping","description":"Your own uninhabited island: hidden-reef snorkeling, night SUP chasing bioluminescent sand, starlit dinner and beach bonfire, gear-free tent stay and a sunrise over the sea.","duration":"13:30 to 08:30 next day","suitable_for":"Island overnight / Unique"},
    {"title":"忘憂島 無人島キャンプ泊","description":"プライベート無人島に滞在。秘境シュノーケリング、夜光砂を追うナイトSUP、星空ディナーとビーチ焚き火、手ぶらテント泊で朝日を迎える1泊2食。","duration":"13:30〜翌8:30","suitable_for":"無人島宿泊／特別体験"},
    {"title":"왕유섬 무인도 캠핑 1박","description":"프라이빗 무인도에서의 하룻밤: 비경 스노클링, 야광사를 쫓는 나이트 SUP, 별빛 만찬과 모닥불, 장비 없이 텐트 숙박 후 일출까지. 1박 2식.","duration":"13:30~익일 08:30","suitable_for":"무인도 숙박 / 특별 체험"},
    {"title":"忘忧岛生态夜泊・无人岛露营","description":"私人无人岛体验：秘境浮潜、SUP 追寻夜光砂、星空晚餐与沙滩营火，免装备入住帐篷，清晨迎接海景日出。","duration":"13:30 至隔日 08:30","suitable_for":"无人岛过夜 / 特殊体验"}), 402),

T(["south-sea"], "東福遊艇 南方四島東嶼坪雙潛點",
  "2023 全新遊艇前進南方四島國家公園：東嶼坪「薰衣草森林」「尼莫珊瑚花園」兩大浮潛點（不會游泳也 OK），下午海上魔毯、SUP、海上溜滑梯或望安登島二選一，龍蝦風味餐與飲料暢飲、海上歡唱。",
  "南方四島 / 浮潛", "一日遊（08:10 報到）", "NT$ 3,600 / 人",
  [{"label":"12 歲以上","value":"NT$ 3,600"},{"label":"4–11 歲","value":"NT$ 3,300"},{"label":"未滿 4 歲","value":"NT$ 1,000"}],
  ["東嶼坪薰衣草森林＋尼莫珊瑚花園雙潛點","水上活動（魔毯／SUP／溜滑梯）或望安登島二選一","梯田式菜宅景觀、在地島民帶路","龍蝦風味餐＋軟飲暢飲＋海上下午茶","全新遊艇：冷氣船艙＋二樓懶人沙發區"],
  "船資、浮潛裝備與水母衣、龍蝦餐、飲料、五項保險",
  "報到：南海遊客中心東福櫃台；浮潛年齡 4–65 歲。"+COMMON_NOTE,
  L({"title":"Dongfu Yacht — Dongyuping Twin Snorkel Spots","description":"Cruise to South Penghu Marine Park on a new yacht: snorkel 'Lavender Forest' and 'Nemo Coral Garden' (non-swimmers welcome), afternoon watersports or Wang'an landing, lobster meal and free-flow drinks.","duration":"Full day","suitable_for":"South isles / Snorkeling"},
    {"title":"東福ヨット 東嶼坪ダブルシュノーケリング","description":"新造ヨットで南方四島国家公園へ。「ラベンダーの森」「ニモのサンゴ園」2大ポイントでシュノーケリング（泳げなくてもOK）、ロブスター料理とドリンク飲み放題。","duration":"1日","suitable_for":"南方四島／シュノーケリング"},
    {"title":"둥푸 요트 둥위핑 더블 스노클링","description":"신형 요트로 남방사도 해양공원으로. '라벤더 숲'과 '니모 산호 정원' 두 포인트 스노클링(수영 못해도 OK), 랍스터 식사와 음료 무제한.","duration":"1일","suitable_for":"남방사도 / 스노클링"},
    {"title":"东福游艇 南方四岛东屿坪双潜点","description":"全新游艇前进南方四岛：薰衣草森林、尼莫珊瑚花园双浮潜点，下午水上活动或望安登岛二选一，龙虾风味餐与饮料畅饮。","duration":"一日游","suitable_for":"南方四岛 / 浮潜"}), 403),

T(["south-sea"], "東福遊艇 南方四島經典三景一日遊",
  "一次看見南方四島最經典的藍：東嶼坪深度導覽含紫色珊瑚礁浮潛、西吉藍洞巡航＋秘境浮潛（含 SUP＋海上魔毯）、西嶼坪與無人島巡航，海人私房午餐與下午茶，偷偷說有龍蝦。",
  "藍洞 / 南方四島精華", "一日遊（08:10 報到）", "NT$ 3,600 / 人",
  [{"label":"12 歲以上","value":"NT$ 3,600"},{"label":"4–11 歲","value":"NT$ 3,300"},{"label":"未滿 4 歲","value":"NT$ 1,000"}],
  ["西吉藍洞巡航（視風浪前往）","東嶼坪紫色珊瑚礁浮潛＋深度導覽","秘境浮潛含 SUP＋海上魔毯","海人私房午餐＋下午茶（有龍蝦）"],
  "船資、浮潛裝備、SUP、午餐下午茶、五項保險",
  "9 人成行；14/18 人座快艇、船上無廁所。"+COMMON_NOTE,
  L({"title":"South Isles Classic Three Sights Day Tour","description":"The classic blues of South Penghu in one day: Dongyuping purple coral snorkeling, Xiji Blue Cave cruising with hidden-spot snorkeling (SUP & sea mat included), and island cruising with a fisherman's lunch.","duration":"Full day","suitable_for":"Blue Cave / Highlights"},
    {"title":"南方四島クラシック三景1日ツアー","description":"東嶼坪の紫サンゴシュノーケリング、西吉ブルーケーブ巡航＋秘境シュノーケリング（SUP・海上マット付き）、海人の絶品ランチ（ロブスター入り）。","duration":"1日","suitable_for":"ブルーケーブ／南方四島"},
    {"title":"남방사도 클래식 3경 원데이","description":"둥위핑 보라 산호 스노클링, 시지 블루케이브 순항+비경 스노클링(SUP·해상 매트 포함), 어부의 프라이빗 런치(랍스터 포함)까지.","duration":"1일","suitable_for":"블루케이브 / 남방사도"},
    {"title":"东福游艇 南方四岛经典三景一日游","description":"东屿坪紫色珊瑚礁浮潜、西吉蓝洞巡航＋秘境浮潜（含 SUP＋海上魔毯）、海人私房午餐与下午茶。","duration":"一日游","suitable_for":"蓝洞 / 南方四岛精华"}), 404),

T(["south-sea"], "蠔野人 南海跳島系列",
  "精緻小船 6 人成團的南海玩法：全球十大秘密島嶼「貓島」虎井嶼半日、薰衣草森林＋海底花園＋望安花宅一日、浪漫暮光旅人夕陽 SUP，與星空花火海上盛宴。全程含自家養殖現蒸牡蠣與酒水飲料。",
  "小團跳島 / 南海", "2 小時～一日（依方案）", "NT$ 1,300 起 / 人",
  [{"label":"跳進貓島虎井半日遊","value":"NT$ 1,800"},{"label":"夢幻紫色珊瑚海（薰衣草＋望安）","value":"NT$ 3,200"},{"label":"浪漫暮光旅人（夕陽場）","value":"NT$ 1,300"},{"label":"星空花火海上盛宴","value":"NT$ 1,600"}],
  ["虎井貓島騎車環島＋玩水 SUP","薰衣草森林、海底花園兩大浮潛點","望安花宅聚落＋網垵口沙灘","海上 PARTY：特調、啤酒汽水暢飲","自家養殖現蒸牡蠣＋海鮮風味餐"],
  "救生衣、面鏡呼吸管（全新咬嘴）、毛巾、餐飲",
  "各方案 6 人成團、上限 12 位，包船另有優惠。"+COMMON_NOTE,
  L({"title":"Oyster Bros South Sea Island Hopping","description":"Small-boat adventures (min 6): Cat Island Hujing half-day, lavender coral & Wang'an day tour, romantic sunset SUP cruise, and starlit fireworks sea party — all with steamed oysters and free-flow drinks.","duration":"2 hrs to full day","suitable_for":"Small-group hopping"},
    {"title":"蠔野人 南海アイランドホッピング","description":"最少6名の小型ボートで、猫島・虎井半日、ラベンダーサンゴ＋望安1日、夕暮れSUPクルーズ、星空花火パーティーなど。蒸し牡蠣とドリンク付き。","duration":"2時間〜1日","suitable_for":"少人数ホッピング"},
    {"title":"오이스터 브로스 남해 섬 호핑","description":"소형 보트(6인 출발): 고양이섬 후징 반나절, 라벤더 산호+왕안 원데이, 선셋 SUP 크루즈, 별빛 불꽃 파티까지. 찐 굴과 음료 무제한 포함.","duration":"2시간~1일","suitable_for":"소그룹 호핑"},
    {"title":"蚝野人 南海跳岛系列","description":"猫岛虎井半日、薰衣草森林＋望安一日、浪漫暮光夕阳 SUP 与星空花火海上盛宴，全程含现蒸牡蛎与酒水饮料。","duration":"2 小时～一日","suitable_for":"小团跳岛 / 南海"}), 405),

T(["south-sea"], "星嶼遊艇 望安薰衣草行程",
  "南方四島遊專門船隊：FUN 潛望安雙點一日（浮潛、SUP、水上魔毯＋望安騎車自由行＋秘境海域再潛一次）、望安薰衣草半日行，以及花火節限定海上賞花火船。",
  "望安 / 薰衣草浮潛", "半日～一日", "NT$ 2,600 起 / 人",
  [{"label":"FUN 潛望安雙點一日遊","value":"NT$ 3,500"},{"label":"望安薰衣草半日行","value":"NT$ 2,600"},{"label":"花火節海上賞花火（20:00–21:20）","value":"線上詢價"}],
  ["薰衣草森林浮潛＋SUP＋水上魔毯","望安登島騎車自由行＋在地美食","無人島欣賞候鳥","秘境海域加碼再潛一次"],
  "裝備、教學、機車（依方案）、保險",
  "集合：南海遊客中心。"+COMMON_NOTE,
  L({"title":"Xingyu Yacht Wang'an Lavender Tours","description":"South-isles specialists: Wang'an twin-spot day tour (snorkel, SUP, sea mat, scooter free-ride and a bonus hidden-reef dip) or a lavender half-day, plus fireworks-viewing cruises in season.","duration":"Half to full day","suitable_for":"Wang'an / Lavender reef"},
    {"title":"星嶼ヨット 望安ラベンダーツアー","description":"望安2ポイント1日ツアー（シュノーケリング・SUP・海上マット＋島内バイク散策＋秘境でもう1泳ぎ）やラベンダー半日、花火鑑賞クルーズも。","duration":"半日〜1日","suitable_for":"望安／ラベンダー礁"},
    {"title":"싱위 요트 왕안 라벤더 투어","description":"왕안 2포인트 원데이(스노클링·SUP·해상 매트+섬 스쿠터 자유여행+비경 추가 입수)와 라벤더 반나절, 불꽃 감상 크루즈까지.","duration":"반나절~1일","suitable_for":"왕안 / 라벤더 산호"},
    {"title":"星屿游艇 望安薰衣草行程","description":"FUN 潜望安双点一日（浮潜、SUP、水上魔毯＋望安骑车自由行）、望安薰衣草半日行与花火节海上赏花火船。","duration":"半日～一日","suitable_for":"望安 / 薰衣草浮潜"}), 406),

T(["south-sea"], "羽之戀 南方四島一日遊",
  "滿 10 人出團的南方四島雙路線：七美 North 抹茶花園＋將軍薰衣草森林雙浮潛，或東吉登島＋將軍薰衣草浮潛＋西吉藍洞巡航；皆含 SUP 立槳與水上摩托車活動、海鮮痛風粥午餐、桶仔雞與野生七星鮑下午茶。",
  "南方四島 / 海鮮饗宴", "一日遊（07:40–08:40 集合）", "NT$ 3,600 / 人",
  [{"label":"成人（兩路線同價）","value":"NT$ 3,600"},{"label":"4–11 歲","value":"NT$ 3,300"},{"label":"0–3 歲","value":"NT$ 1,000"}],
  ["七美抹茶花園＋將軍薰衣草森林雙潛點","或東吉登島＋西吉藍洞巡航","SUP 立槳＋水上摩托車活動","午餐海鮮痛風粥；下午茶桶仔雞＋野生七星鮑","含自潛裝備、飲品與船上餅乾"],
  "浮潛裝備（含自潛）、餐食、公共意外險與乘客險",
  "四月份水溫風浪不佳時七美浮潛改為登島；遇颱風提供替代方案或全額退費。"+COMMON_NOTE,
  L({"title":"Yuzhilian South Isles Day Tour","description":"Two routes (min 10): Qimei 'Matcha Garden' + General Lavender twin snorkel, or Dongji landing + Blue Cave cruise — with SUP, jet-ski fun, seafood congee lunch and abalone afternoon tea.","duration":"Full day","suitable_for":"South isles / Seafood feast"},
    {"title":"羽之戀 南方四島1日ツアー","description":"2ルート（10名催行）：七美「抹茶ガーデン」＋将軍ラベンダーのWシュノーケリング、または東吉上陸＋西吉ブルーケーブ。海鮮粥ランチとアワビの午後茶付き。","duration":"1日","suitable_for":"南方四島／海鮮"},
    {"title":"위즈롄 남방사도 원데이","description":"2개 루트(10인 출발): 치메이 '말차 가든'+장군 라벤더 더블 스노클링 또는 둥지 상륙+블루케이브 순항. 해물죽 점심과 전복 애프터눈 티 포함.","duration":"1일","suitable_for":"남방사도 / 해산물"},
    {"title":"羽之恋 南方四岛一日游","description":"七美抹茶花园＋将军薰衣草双浮潜，或东吉登岛＋西吉蓝洞巡航；含 SUP 与水上摩托车、海鲜痛风粥午餐、桶仔鸡与野生七星鲍下午茶。","duration":"一日游","suitable_for":"南方四岛 / 海鲜飨宴"}), 407),

T(["south-sea"], "宏星 七美錦鯉灣浮潛一日遊",
  "專船直達七美停留 4.5–5 小時：鯉灣臥牛生態浮潛區體驗世界級珊瑚礁與小丑魚（浮潛或彩色獨木舟二選一），環島機車自由行探訪雙心石滬、小台灣、望夫石，回程加碼桶盤嶼巡航。",
  "七美 / 雙心石滬", "約 8 小時（08:00 開船）", "NT$ 1,800 / 人",
  [{"label":"一日遊（浮潛或獨木舟）","value":"NT$ 1,800"},{"label":"一日遊（不玩水）","value":"NT$ 1,300"},{"label":"3 歲以下","value":"NT$ 150"},{"label":"馬公–七美單程船票","value":"NT$ 500"}],
  ["鯉灣臥牛浮潛區：世界級珊瑚礁群","浮潛或彩色獨木舟二選一","含七美機車兩人一部（含油）","雙心石滬、小台灣、望夫石環島自由行","回程桶盤嶼巡航"],
  "來回船票、機車、浮潛裝備（含近視面鏡）、水域責任險",
  "報到：南海遊客中心海安櫃台（宏星報到處）。"+COMMON_NOTE,
  L({"title":"Hongxing Qimei Snorkeling Day Tour","description":"Direct boat to Qimei with 4.5–5 hours on-island: world-class coral snorkeling (or colorful kayak) at Liwan bay, scooter free-ride to the Twin-Hearts Stone Weir, plus a Tongpan Islet cruise.","duration":"About 8 hrs","suitable_for":"Qimei / Twin Hearts Weir"},
    {"title":"宏星 七美シュノーケリング1日ツアー","description":"専用船で七美へ直行、島滞在4.5〜5時間。世界級のサンゴ礁でシュノーケリング（またはカラフルカヌー）、バイクでダブルハート石滬巡り、桶盤嶼クルーズ付き。","duration":"約8時間","suitable_for":"七美／ダブルハート"},
    {"title":"훙싱 치메이 스노클링 원데이","description":"전용선으로 치메이 직행, 섬 체류 4.5~5시간. 세계급 산호초 스노클링(또는 컬러 카약), 스쿠터로 쌍심석호 자유여행, 퉁판섬 크루즈까지.","duration":"약 8시간","suitable_for":"치메이 / 쌍심석호"},
    {"title":"宏星 七美锦鲤湾浮潜一日游","description":"专船直达七美停留 4.5–5 小时：锦鲤湾世界级珊瑚礁浮潜或彩色独木舟，环岛机车自由行探访双心石沪，回程桶盘屿巡航。","duration":"约 8 小时","suitable_for":"七美 / 双心石沪"}), 408),
]

def main():
    url = sys.argv[1]
    conn = psycopg2.connect(url)
    cur = conn.cursor()
    added, skipped = 0, 0
    for t in TOURS:
        cur.execute("SELECT 1 FROM tours WHERE title=%s", (t["title"],))
        if cur.fetchone():
            skipped += 1
            continue
        for lang in t["i18n"].values():
            if "duration" in lang:
                lang["duration"] = lang["duration"][:30]
        cur.execute("""INSERT INTO tours
            (tabs,title,description,suitable_for,duration,price_display,prices,modal_data,i18n,sort_order,is_active,badge_text,badge_class,image_url)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,TRUE,%s,%s,%s)""",
            (json.dumps(t["tabs"], ensure_ascii=False), t["title"][:120], t["description"],
             t["suitable_for"][:120], t["duration"][:30], t["price_display"][:60],
             json.dumps(t["prices"], ensure_ascii=False),
             json.dumps(t["modal_data"], ensure_ascii=False),
             json.dumps(t["i18n"], ensure_ascii=False),
             t["sort_order"], "2026 公會精選", "", ""))
        added += 1
    conn.commit()
    cur.close(); conn.close()
    print(f"added={added} skipped={skipped} total={len(TOURS)}")

if __name__ == "__main__":
    main()
